### ISSUE TITLE
Dropbox: rclone repeatedly uploads the same file even though the file has the same content as the old file but a different modification time

### ISSUE THREAD

**Issue by MoodyMoon** [ncw/rclone#2218]
#### What is the problem you are having with rclone?
rclone repeatedly uploads the same file even though the file has the same content (same checksum) as the old file but a different modification time.

##### How to reproduce
1. Create a text file with one character in it.
2. Wait until files are synchronised.
3. Wait for a period of time larger than `--max-window`.
4. Modify the file modification time without modifying the content.
5. Sync using rclone.
6. Sync again to see it being re-uploaded.
Note that the modification time shown on the Dropbox web interface will not change after synchronisation using rclone.

#### What is your rclone version
Problem is reproducible on both rclone stable v1.40 and rclone beta.
```
rclone v1.40-045-g0358e9e7
- os/arch: windows/amd64
- go version: go1.10
```

#### Which OS you are using and how many bits
Windows 7 SP1, 64 bit

####  Which cloud storage system are you using?
Dropbox

#### The command you were trying to run
Please refer to the log below.

#### A log from the command with the `-vv` flag
```
2018/04/06 15:35:51 DEBUG : rclone: Version "v1.40-045-g0358e9e7" starting with parameters ["<omitted>\\rclone\\rclone.exe" "sync" "-vv" "--checkers=2" "--config" "cf" "--delete-during" "--modify-window=2m" "--stats=5s" "--transfers=2" "--verbose" "C:\\Users\\<omitted>\\Dropbox\\Test" "<omitted>:Test"]
2018/04/06 15:35:51 DEBUG : Using config file from "<omitted>"
2018/04/06 15:35:52 INFO  : Dropbox root 'Test': Modify window is 2m0s
2018/04/06 15:35:52 INFO  : Waiting for deletions to finish
2018/04/06 15:35:53 DEBUG : a.txt: Modification times differ by -3m39.4866604s:
2018-04-06 15:27:46.4866604 +0800 +08, 2018-04-06 07:24:07 +0000 UTC
2018/04/06 15:35:53 INFO  : Dropbox root 'Test': Waiting for checks to finish
2018/04/06 15:35:53 DEBUG : a.txt: src and dst identical but can't set mod time without re-uploading
2018/04/06 15:35:53 INFO  : Dropbox root 'Test': Waiting for transfers to finish

2018/04/06 15:35:54 INFO  : a.txt: Copied (replaced existing)
2018/04/06 15:35:54 INFO  :
Transferred:      1 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 1
Transferred:            1
Elapsed time:       19.7s

2018/04/06 15:35:54 DEBUG : 6 go routines active
2018/04/06 15:35:54 DEBUG : rclone: Version "v1.40-045-g0358e9e7" finishing with parameters ["<omitted>\\rclone\\rclone.exe" "sync" "-vv" "--checkers=2" "--config" "cf" "--delete-during" "--modify-window=2m" "--stats=5s" "--transfers=2" "--verbose" "C:\\Users\\<omitted>\\Dropbox\\Test" "<omitted>:Test"]
```

**Comment by ncw** [comment]
Thanks for tracking that down and the nice reproduction.  I can verify that.

Dropbox can't set modification times on files without uploading them again.  Unfortunately dropbox has a bug where if you upload the same file with the same contents but a different modification time, it doesn't update the modification time.

To work around this, rclone should delete the existing file first - that is what v1.39 did anyway.

However in the process of fixing #2134 - dfd0f4c5a458b88857be4a035d910ffc5934f6eb it stopped deleting the file before  upload and caused this issue.

I think it is just a case of reverting one hunk of the diff which got committed by accident, but I'll have to test first.

**Comment by ncw** [comment]
Here is some test code for you to try:

https://beta.rclone.org/v1.40-048-gc749cf8d-test/ (uploaded in 15-30 mins)

Which should fix this problem.

**Comment by MoodyMoon** [comment]
I am not sure why but I can't seem to reproduce the problem anymore today using rclone stable v1.40. Maybe Dropbox has already fixed it. The test binaries above works fine too. However, the modification time on Dropbox web interface still does not change.
