### ISSUE TITLE
failed to open source object: open file failed: cannotDownloadAbusiveFile

### ISSUE THREAD

**Issue by KrLx1994roller** [ncw/rclone#2317]
#### What is the problem you are having with rclone?
When trying to download some APK or EXE files that I have on GDrive, I receive this error message: 

`file: Failed to copy: failed to open source object: open file failed: googleapi: Error 403: This file has been identified as malware or spam and cannot be downloaded., cannotDownloadAbusiveFile`

#### What is your rclone version (eg output from `rclone -V`)
rclone v1.41
- os/arch: darwin/amd64
- go version: go1.10

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
macOS High Sierra 10.13.4

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync remote:folder local/Folder

#### Possible solution
If we add the flag `acknowledgeAbuse=true` we can bypass this error: https://github.com/prasmussen/gdrive/issues/182

**Comment by ncw** [comment]
Looks easy enough.. Fancy sending a PR?

**Comment by KrLx1994roller** [comment]
I have no idea about `Go` but I'll take a look at it :)

**Comment by jahands** [comment]
I would very much appreciate this. I have a ton of legitimate files getting flagged as abusive.

**Comment by ncw** [comment]
OK I've implemented this.

I can't test it though as I don't have any abusive files!

So can you

   * Attempt to download an abusive file.  You should get an error which includes the text "Use the --drive-acknowledge-abuse flag to download this file"
  * Try downloading again with the  `--drive-acknowledge-abuse` flag and check it does download!

Thanks

https://beta.rclone.org/v1.41-090-g6be5a989-fix-2317-drive-abuse/ (uploaded in 15-30 mins)

**Comment by albert2742** [comment]
without --drive-ackowledge-abuse:

2018/06/08 10:53:25 INFO  : Local file system at /tmp/A.Robot.Named.Fight.v1.1.2.16-SiMPLEX: Waiting for checks to finish
2018/06/08 10:53:25 INFO  : Local file system at /tmp/A.Robot.Named.Fight.v1.1.2.16-SiMPLEX: Waiting for transfers to finish
2018/06/08 10:53:25 ERROR : SiMPLEX.exe: Failed to copy: failed to open source object: open file failed: Use the --drive-acknowledge-abuse flag to download this file: googleapi: Error 403: This file has been identified as malware or spam and cannot be downloaded., cannotDownloadAbusiveFile
2018/06/08 10:53:25 INFO  : SiMPLEX.ini: Copied (new)
2018/06/08 10:53:25 INFO  : bassmod.dll: Copied (new)
2018/06/08 10:53:25 INFO  : simplex.nfo: Copied (new)
2018/06/08 10:53:26 INFO  : unarc.exe: Copied (new)
2018/06/08 10:53:31 INFO  : SiMPLEX.bin: Copied (new)
2018/06/08 10:53:31 ERROR : Attempt 1/3 failed with 1 errors and: failed to open source object: open file failed: Use the --drive-acknowledge-abuse flag to download this file: googleapi: Error 403: This file has been identified as malware or spam and cannot be downloaded., cannotDownloadAbusiveFile
2018/06/08 10:53:31 INFO  : Local file system at /tmp/A.Robot.Named.Fight.v1.1.2.16-SiMPLEX: Waiting for checks to finish
2018/06/08 10:53:31 INFO  : Local file system at /tmp/A.Robot.Named.Fight.v1.1.2.16-SiMPLEX: Waiting for transfers to finish
2018/06/08 10:53:31 ERROR : SiMPLEX.exe: Failed to copy: failed to open source object: open file failed: Use the --drive-acknowledge-abuse flag to download this file: googleapi: Error 403: This file has been identified as malware or spam and cannot be downloaded., cannotDownloadAbusiveFile
2018/06/08 10:53:31 ERROR : Attempt 2/3 failed with 1 errors and: failed to open source object: open file failed: Use the --drive-acknowledge-abuse flag to download this file: googleapi: Error 403: This file has been identified as malware or spam and cannot be downloaded., cannotDownloadAbusiveFile
2018/06/08 10:53:31 INFO  : Local file system at /tmp/A.Robot.Named.Fight.v1.1.2.16-SiMPLEX: Waiting for checks to finish
2018/06/08 10:53:31 INFO  : Local file system at /tmp/A.Robot.Named.Fight.v1.1.2.16-SiMPLEX: Waiting for transfers to finish
2018/06/08 10:53:32 ERROR : SiMPLEX.exe: Failed to copy: failed to open source object: open file failed: Use the --drive-acknowledge-abuse flag to download this file: googleapi: Error 403: This file has been identified as malware or spam and cannot be downloaded., cannotDownloadAbusiveFile
2018/06/08 10:53:32 ERROR : Attempt 3/3 failed with 1 errors and: failed to open source object: open file failed: Use the --drive-acknowledge-abuse flag to download this file: googleapi: Error 403: This file has been identified as malware or spam and cannot be downloaded., cannotDownloadAbusiveFile
2018/06/08 10:53:32 Failed to copy: failed to open source object: open file failed: Use the --drive-acknowledge-abuse flag to download this file: googleapi: Error 403: This file has been identified as malware or spam and cannot be downloaded., cannotDownloadAbusiveFile

with flag:

`2018/06/08 10:54:56 ERROR : bassmod.dll: Failed to copy: failed to open source object: open file failed: googleapi: Error 403: This file has not been flagged for abuse., invalidAbuseAcknowledgment
2018/06/08 10:54:56 ERROR : SiMPLEX.ini: Failed to copy: failed to open source object: open file failed: googleapi: Error 403: This file has not been flagged for abuse., invalidAbuseAcknowledgment
2018/06/08 10:54:56 ERROR : simplex.nfo: Failed to copy: failed to open source object: open file failed: googleapi: Error 403: This file has not been flagged for abuse., invalidAbuseAcknowledgment
2018/06/08 10:54:56 ERROR : unarc.exe: Failed to copy: failed to open source object: open file failed: googleapi: Error 403: This file has not been flagged for abuse., invalidAbuseAcknowledgment
2018/06/08 10:54:58 ERROR : SiMPLEX.bin: Failed to copy: failed to open source object: open file failed: googleapi: Error 403: This file has not been flagged for abuse., invalidAbuseAcknowledgment
2018/06/08 10:54:58 ERROR : Attempt 1/3 failed with 5 errors and: failed to open source object: open file failed: googleapi: Error 403: This file has not been flagged for abuse., invalidAbuseAcknowledgment
2018/06/08 10:54:59 ERROR : SiMPLEX.ini: Failed to copy: failed to open source object: open file failed: googleapi: Error 403: This file has not been flagged for abuse., invalidAbuseAcknowledgment
2018/06/08 10:54:59 ERROR : simplex.nfo: Failed to copy: failed to open source object: open file failed: googleapi: Error 403: This file has not been flagged for abuse., invalidAbuseAcknowledgment
2018/06/08 10:54:59 ERROR : unarc.exe: Failed to copy: failed to open source object: open file failed: googleapi: Error 403: This file has not been flagged for abuse., invalidAbuseAcknowledgment
2018/06/08 10:54:59 ERROR : bassmod.dll: Failed to copy: failed to open source object: open file failed: googleapi: Error 403: This file has not been flagged for abuse., invalidAbuseAcknowledgment
2018/06/08 10:55:08 ERROR : SiMPLEX.bin: Failed to copy: failed to open source object: open file failed: googleapi: Error 403: This file has not been flagged for abuse., invalidAbuseAcknowledgment
2018/06/08 10:55:08 ERROR : Attempt 2/3 failed with 5 errors and: failed to open source object: open file failed: googleapi: Error 403: This file has not been flagged for abuse., invalidAbuseAcknowledgment
2018/06/08 10:55:12 ERROR : bassmod.dll: Failed to copy: failed to open source object: open file failed: googleapi: Error 403: This file has not been flagged for abuse., invalidAbuseAcknowledgment
2018/06/08 10:55:12 ERROR : simplex.nfo: Failed to copy: failed to open source object: open file failed: googleapi: Error 403: This file has not been flagged for abuse., invalidAbuseAcknowledgment
2018/06/08 10:55:12 ERROR : SiMPLEX.ini: Failed to copy: failed to open source object: open file failed: googleapi: Error 403: This file has not been flagged for abuse., invalidAbuseAcknowledgment
2018/06/08 10:55:12 ERROR : unarc.exe: Failed to copy: failed to open source object: open file failed: googleapi: Error 403: This file has not been flagged for abuse., invalidAbuseAcknowledgment
2018/06/08 10:55:33 ERROR : SiMPLEX.bin: Failed to copy: failed to open source object: open file failed: googleapi: Error 403: This file has not been flagged for abuse., invalidAbuseAcknowledgment
2018/06/08 10:55:33 ERROR : Attempt 3/3 failed with 5 errors and: failed to open source object: open file failed: googleapi: Error 403: This file has not been flagged for abuse., invalidAbuseAcknowledgment
2018/06/08 10:55:33 Failed to copy: failed to open source object: open file failed: googleapi: Error 403: This file has not been flagged for abuse., invalidAbuseAcknowledgment
`

**Comment by KrLx1994roller** [comment]
So it looks like when we receive the error `cannotDownloadAbusiveFile ` we then should retry but adding the `--drive-acknowledge-abuse` flag...

**Comment by albert2742** [comment]
FYI v2 API does no have this issue if the file is abusive, it downloads it regardless.

**Comment by albert2742** [comment]
So, if you use the flag, abusive files do download but non-abusive files will not. I have lots of mixed files so this doesn't help much :/

**Comment by ncw** [comment]
Thanks for testing.  I will revise the patch!

**Comment by jahands** [comment]
If you do keep it as a flag, I'd like it if the drive remote had an option
to download all abusive files. Otherwise every copy/sync I do I'll have to
add the flag because I don't know which folders have "abusive" files.

There are no instances in any of my rclone+drive use-cases where I want to
be "protected" from "abusive" files.

**Comment by ncw** [comment]
OK here is a revised patch which tries the download without the query parameter and if it fails with that error, retries it with the query parameter if you supply the --drive-acknowledge-abuse flag.

Can you do the two tests again please?

   * Attempt to download an abusive file.  You should get an error which includes the text "Use the --drive-acknowledge-abuse flag to download this file"
  * Try downloading again with the  `--drive-acknowledge-abuse` flag and check it does download!

Here is a beta to try

https://beta.rclone.org/v1.41-092-g3bf9c26a-fix-2317-drive-abuse/ (uploaded in 15-30 mins)

@jahands wrote:
> If you do keep it as a flag, I'd like it if the drive remote had an option
to download all abusive files

My reading of the API docs makes me thing that I shouldn't be doing this all the time - the user will have to do something to download the file.

The --drive-acknowledge-abuse flag if supplied will allow all abusive files to be downloaded.  You can set this in an environment variable `RCLONE_DRIVE_ACKNOWLEDGE_ABUSE=true`.  When I've finished the config restructure (after 1.42 is released) you'll be able to put it in the config file too.

> Files identified as abusive (malware, etc.) are only downloadable by the owner. Additionally, the query parameter acknowledgeAbuse=true must be included to indicate that the user has acknowledged the risk of downloading potential malware. Your application should interactively warn the user before using this query parameter.

**Comment by jahands** [comment]
I would consider a user setting an environment variable or setting it in
the config file to be user consent.

**Comment by KrLx1994roller** [comment]
I think that the approach taken is the perfect one. Great job @ncw, too bad that I cannot test it now.

**Comment by jahands** [comment]
I agree I like the latest revision. I'll test it later today.

**Comment by albert2742** [comment]
@ncw Tested the new beta and it is indeed working!

**Comment by ncw** [comment]
@jahands how did your testing go?  Shall I merge this fix?

**Comment by jahands** [comment]
Works great!

## Without flag:
```
rclone-v1.41-092-g3bf9c26a-fix-2317-drive-abuse-windows-amd64\rclone.exe -v copy gd:<REDACTED>/igfxrcht.lrc .
2018/06/10 08:16:20 ERROR : igfxrcht.lrc: Failed to copy: failed to open source object: open file failed: Use the --drive-acknowledge-abuse flag to download this file: googleapi: Error 403: This file has been identified as malware or spam and cannot be downloaded., cannotDownloadAbusiveFile
2018/06/10 08:16:20 ERROR : Attempt 1/3 failed with 1 errors and: failed to open source object: open file failed: Use the --drive-acknowledge-abuse flag to download this file: googleapi: Error 403: This file has been identified as malware or spam and cannot be downloaded., cannotDownloadAbusiveFile
2018/06/10 08:16:21 ERROR : igfxrcht.lrc: Failed to copy: failed to open source object: open file failed: Use the --drive-acknowledge-abuse flag to download this file: googleapi: Error 403: This file has been identified as malware or spam and cannot be downloaded., cannotDownloadAbusiveFile
2018/06/10 08:16:21 ERROR : Attempt 2/3 failed with 1 errors and: failed to open source object: open file failed: Use the --drive-acknowledge-abuse flag to download this file: googleapi: Error 403: This file has been identified as malware or spam and cannot be downloaded., cannotDownloadAbusiveFile
2018/06/10 08:16:21 ERROR : igfxrcht.lrc: Failed to copy: failed to open source object: open file failed: Use the --drive-acknowledge-abuse flag to download this file: googleapi: Error 403: This file has been identified as malware or spam and cannot be downloaded., cannotDownloadAbusiveFile
2018/06/10 08:16:21 ERROR : Attempt 3/3 failed with 1 errors and: failed to open source object: open file failed: Use the --drive-acknowledge-abuse flag to download this file: googleapi: Error 403: This file has been identified as malware or spam and cannot be downloaded., cannotDownloadAbusiveFile
2018/06/10 08:16:21 Failed to copy: failed to open source object: open file failed: Use the --drive-acknowledge-abuse flag to download this file: googleapi: Error 403: This file has been identified as malware or spam and cannot be downloaded., cannotDownloadAbusiveFile
```

## With flag:
```
rclone-v1.41-092-g3bf9c26a-fix-2317-drive-abuse-windows-amd64\rclone.exe -v copy gd:<REDACTED>/igfxrcht.lrc . --drive-acknowledge-abuse
2018/06/10 08:16:38 INFO  : igfxrcht.lrc: Copied (new)
2018/06/10 08:16:38 INFO  :
Transferred:   421 kBytes (32.407 kBytes/s)
Errors:                 0
Checks:                 0
Transferred:            1
Elapsed time:       12.9s
```

**Comment by jahands** [comment]
I also tried copying a non abusive file with the flag and that worked also.
LGTM

**Comment by ncw** [comment]
Thanks to you all for testing :-)

I've merged this here:

https://beta.rclone.org/v1.41-098-g9289aead/ (uploaded in 15-30 mins)

and it will be in [the latest beta](https://beta.rclone.org) from now on and v1.42.

**Comment by jahands** [comment]
Can you run it again with -vv and post the output here?

**Comment by Fabian42** [comment]
Oh wait, the file wasn't even on Google Drive. Nevermind.
Tested again and it works. Thank you!

**Comment by Fabian42** [comment]
By having it be a command line argument, scripting programs like RCloneSync
still don't work. It would be better as an option in `rclone config` or
something else that's permanent.
Should this be reopened or should I make a new report?

**Comment by ncw** [comment]
@Fabian42 thanks for testing.  You can set it as an environment variable for now - you'll be able to set it in the config file in about a week after v1.41 is released (I'll merge my config unification changes once v1.41 is released).
