### ISSUE TITLE
rclone cannot read an encfs mounted drive on Windows 7

### ISSUE THREAD

**Issue by garypaduana** [ncw/rclone#261]
First mount the virtual drive using encfs

    encfs --reverse h:/folder n:

Try to perform any operation with that drive using rclone and it will return with a read error.  `dir` from the `N:\` directory works without a problem.

    N:\>rclone ls .
    2015/12/24 12:00:39 Local file system at \\?\N:\: Failed to open directory: \\?\N:\: Readdir \\?\N:\: The system cannot find the path specified.
    
    Transferred:            0 Bytes (   0.00 kByte/s)
    Errors:                 1
    Checks:                 0
    Transferred:            0
    Elapsed time:           0
    
    N:\>

I'm using Windows 7 Professional x64, encfs4win, and Dokan 0.6.0

[encfs.zip](https://github.com/ncw/rclone/files/71905/encfs.zip)

[DokanInstall_0.6.0.zip](https://github.com/ncw/rclone/files/71906/DokanInstall_0.6.0.zip)

**Comment by ncw** [comment]
Hmm looks like it might be related to @klauspost windows file name unification? Klaus?

**Comment by klauspost** [comment]
@garypaduana - This is likely a Dokan bug. It is old and unmaintained, just as encfs4win, if you are using [this version](http://members.ferrara.linux.it/freddy77/encfs.html).

Have you tried some of the more recent EncFS software like this: http://encfsmp.sourceforge.net ?

**Comment by garypaduana** [comment]
@klauspost Thank you for this suggestion but unfortunately it also does not work.  It is possibly a step in the right direction, though, since drives mounted with EncfsMP are considered to be local drives and not removable storage.

Also, EncfsMP does not support the `--reverse` option, which would break the current backup workflow I'm using.

My current workaround is to share the folders over smb then run encfs and rclone from a linux VM.

Thanks
![disks](https://cloud.githubusercontent.com/assets/4510602/12075915/5f8a127e-b147-11e5-8bc6-14357b8c2e44.PNG)
![encfsmp](https://cloud.githubusercontent.com/assets/4510602/12075916/5f9157aa-b147-11e5-8594-3f41f2050b49.PNG)
![rclone](https://cloud.githubusercontent.com/assets/4510602/12075917/5f977e1e-b147-11e5-8e70-6ec59480007e.PNG)

**Comment by klauspost** [comment]
Does it work, if you clone from a subdirectory?

**Comment by garypaduana** [comment]
Yes, it does work when using EncfsMP, but not with Dokan.

EncfsMP:

<img width="1250" alt="screen shot 2016-01-02 at 12 50 18 pm" src="https://cloud.githubusercontent.com/assets/4510602/12076060/a17ef3cc-b14f-11e5-9fbb-69eaf0c1a4d0.png">

Dokan (with `--reverse`)

<img width="1675" alt="screen shot 2016-01-02 at 12 50 51 pm" src="https://cloud.githubusercontent.com/assets/4510602/12076063/b2d49dc0-b14f-11e5-9359-4599cc127898.png">

**Comment by garypaduana** [comment]
Also, I'm able to programmatically access the mounted drive from the root path as seen here with Groovy:

![groovy](https://cloud.githubusercontent.com/assets/4510602/12077211/9d399d2a-b18c-11e5-9456-3ea63060ff6a.PNG)

**Comment by klauspost** [comment]
It must be programmatically accessible using a [UNC path](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#maxpath).

All paths are converted to UNC paths, otherwise we get into trouble with paths longer than 255 bytes.

I will look at the EncfsMP root problem tomorrow.

**Comment by klauspost** [comment]
Really the file system drivers should be fixed. 

However, since that probably isn't something you can do, I have added an option to disable UNC path conversion. See PR #271.

**Comment by garypaduana** [comment]
Thank you very much for the fix! I look forward to using it.

**Comment by klauspost** [comment]
@garypaduana - I have attached a build with the nounc option for you to test. I only have EncFSMP, 

[rclone-nounc-test.zip](https://github.com/ncw/rclone/files/78203/rclone-nounc-test.zip)

Documentation is here: https://github.com/klauspost/rclone/blob/add-nounc-option/docs/content/local.md#long-paths-on-windows

**Comment by garypaduana** [comment]
@klauspost I tried to use the fix this morning but unfortunately it doesn't seem to have worked.  As you can see it is no longer using the UNC path but still cannot find the path specified in the encfs drive.  

I'm able to access the mounted drive with every other software I frequently use (SyncBackPro, Amazon Cloud Drive Official Client, VLC, Filezilla FTP Server, SMB shares, various image viewers, 7zip, Search Everything, and so on).  Is there anything else you'd like me to try?

Thank you for your continued effort but if you want to put this on hold I understand.

    N:\>rclone ls .
    2016/01/05 15:04:25 Local file system at N:\: Failed to open directory: N:\: Readdir N:\: The system cannot find the path specified.

    Transferred:            0 Bytes (   0.00 kByte/s)
    Errors:                 1
    Checks:                 0
    Transferred:            0
    Elapsed time:           0

Trying again with a subdirectory:

    N:\>cd "PjxNNGtyqk8EISnAH58A,fI,"

    N:\PjxNNGtyqk8EISnAH58A,fI,>dir
     Volume in drive N is DOKAN

     Directory of N:\PjxNNGtyqk8EISnAH58A,fI,

    01/02/2015  12:53 PM    <DIR>          2haehT9H7yiX1nj9aqo1lOOA
    01/02/2015  12:53 PM    <DIR>          ejb0kh2oADu6vrJqiqcyq-Yn
    01/02/2015  12:54 PM    <DIR>          -yKOSOU2DrPVaZ1i1-P7Ox3e
    01/02/2015  12:55 PM    <DIR>          8hmzPOFgvBj,st4UCVbvP8Wr
    01/02/2015  12:55 PM    <DIR>          qPrXtL3uqPmYk5-GO-Q7fHiP
    01/02/2015  12:56 PM    <DIR>          4zrbvqYzJBzYcCsWxiT66W8r
    01/02/2015  12:56 PM    <DIR>          YF23wJEzBDUbWhEqVaj4Upky
    01/02/2015  12:57 PM    <DIR>          3,92vmHkguZXZgaGSmJd,fqy
                   0 File(s)              0 bytes
                   8 Dir(s)  363,137,863,680 bytes free

    N:\PjxNNGtyqk8EISnAH58A,fI,>rclone ls .
    2016/01/05 15:06:43 Local file system at N:\PjxNNGtyqk8EISnAH58A,fI,: Failed to open directory: N:\PjxNNGtyqk8EISnAH58A,fI,: Readdir N:\PjxNNGtyqk8EISnAH58A,fI,: The system cannot find the path specified.

    Transferred:            0 Bytes (   0.00 kByte/s)
    Errors:                 1
    Checks:                 0
    Transferred:            0
    Elapsed time:           0

**Comment by klauspost** [comment]
The colon is added by the error printer, so it is not part of the requested path.

It seems like this check in Go [file_windows.go](https://github.com/golang/go/blob/master/src/os/file_windows.go#L204) is failing. That is the error returned. My guess is that Dokan/EncFS is returning the wrong information. I will create a test binary for you.

**Comment by klauspost** [comment]
Here is a small test to run, that might give us something more to work with: [test.zip](https://github.com/ncw/rclone/files/79771/test.zip)

I have put the source code [here](https://gist.github.com/klauspost/5f87caf402a8abf369d5) if you would rather compile it yourself.

Please run it, and paste the output here, then hopefully we have something to work with.

**Comment by garypaduana** [comment]
N:\>c:/users/gary/desktop/test.exe
    Current dir: "N:\"
    Main dir Stat:
    Name "\"
    Size 0
    IsDir true
    Mode.IsDir true
    Mode.IsRegular false
    Mode.String drwxrwxrwx
    Mode.Perm: -rwxrwxrwx
    2016/01/06 23:12:59 ioutil.ReadDirReaddir N:\: The system cannot find the path specified.

    N:\>

**Comment by klauspost** [comment]
ok, it is somewhere in the [directory reading code](https://github.com/golang/go/blob/master/src/os/file_windows.go#L92), most likely Dokan returning a wrong value somewhere. 

The only way I can see this triggering is if [opening the directory as a file](https://github.com/golang/go/blob/master/src/os/file_windows.go#L84) does NOT return an error. 

Go first tries to open a file as a plain file, if that fails, it tries as a directory before failing. It seems like Dokan/encfs reports "success" when opening `z:\` as a file, which it shouldn't, since it isn't a file.

There isn't much we can do from here. You can try filing a bug for Go, but I doubt they will include a workaround for (what I expect to be) a buggy filesystem driver. It may be fixed in DokanY, but I don't know if encfs4win has been compiled for DokanY.

Another workaround that could work, could be to share the drive, and access it as `\\localmachine\share`, though that is unlikely to make any difference.

**Comment by garypaduana** [comment]
@klauspost I appreciate all the work you put into investigating this.  I understand I'm using old software that hasn't been updated for years but only Dokan 0.6.0 is supported by encfs4win.  As I mentioned earlier my workaround is to share the drive and run encfs and rclone inside an ubuntu VM.  This works great and is really just a minor inconvenience.  

Thank you

**Comment by Liryna** [comment]
@klauspost thank you for the test sample ❤️ I have fixed the issue faced on dokan. https://github.com/dokan-dev/dokany/issues/406 👍
