### ISSUE TITLE
Copying fails when google cloud buckets have "Bucket Policy Only" enabled

### ISSUE THREAD

**Issue by daltschu22** [ncw/rclone#3014]
#### What is the problem you are having with rclone?
Buckets that are set to "Bucket Policy Only" will not accept files being copied into them, since rclone attempts to set an object level ACL.

Ive attempted to get around this by defining an empty string using `--gcs-object-acl`, but only this list is allowed:
Allowed values: [authenticatedread, bucketownerfullcontrol, bucketownerread, private, projectprivate, publicread]

This google cloud storage feature is new, and optional on new buckets, but breaks the usage of rclone if put to use.
https://cloud.google.com/storage/docs/bucket-policy-only?hl=en_US

#### What is your rclone version (output from `rclone version`)
rclone v1.43-113-g527c0af1-beta
#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
RHEL 7.4, 64 bit
####  Which cloud storage system are you using? (eg Google Drive)
Google Cloud Storage
#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy
#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
Failed to copy: googleapi: Error 400: Cannot use ACL API to set object policy when object policies are disabled., invalid

**Comment by ncw** [comment]
Did you try editing the config to set an empty string for the object ACL?

Do you think a new object ACL type is needed? Say bucketpolicyonly or something like that?

Did you try the latest beta? It will be using a later version of the SDK which could help.

**Comment by daltschu22** [comment]
Thanks for getting back so quick. 

`Did you try the latest beta? It will be using a later version of the SDK which could help.`
Just pulled the latest:
`rclone v1.46.0-053-gd233efbf-beta
- os/arch: linux/amd64
- go version: go1.12`

**Did you try editing the config to set an empty string for the object ACL?**
I just tried this. Heres my current config (Ive tried all sorts of different variations to fix this, none successful)

```
[test-perms]
type = google cloud storage
client_id =
client_secret =
project_number = **********
service_account_file = /****/****/****/****
object_acl = ""
bucket_acl = private
location = us-east4
storage_class = REGIONAL

```
This results in:
`Failed to copy: googleapi: Error 400: Invalid string value: '""'. Allowed values: [authenticatedread, bucketownerfullcontrol, bucketownerread, private, projectprivate, publicread], invalidParameter`

My GO experience is limited, so apologies if this is wrong, but I believe the code preventing the empty string is:
https://github.com/ncw/rclone/blob/master/backend/googlecloudstorage/googlecloudstorage.go#L364-L366

**Do you think a new object ACL type is needed? Say bucketpolicyonly or something like that?**
This is an interesting question. I guess it matters how you would like to handle something like this in rclone. 

Im pouring over the docs to try and figure out how to architect this. But according to the document:
`Requests to set, read, or modify bucket and object ACLs fail with 400 Bad Request errors.`
So it seems its both bucket and object ACL's that will no longer work.
IAM is the concept used to control permissions everywhere else inside google cloud, the only exceptions is buckets/objects. So it makes sense they are moving towards supporting the IAM model.

So it seems in order to support this setting you would need to move away from using ACL's over to IAM entirely if you find that this setting is enabled.

If you query the buckets metadata it does indeed return that it has this policy enabled
` "iamConfiguration": {
  "bucketPolicyOnly": {
   "enabled": true,`
So its a thing we can discover before trying to copy files. 

Its possible you might want to have a setting in the config for GCS that will define `bucketpolicyonly = true` and that would switch things over to using IAM. But then would we define each IAM policy in the config also? Im not sure.

Im going to continue digging through the documentation to see if we can wholesale translate the "canned ACL's" that rclone normally uses into IAM roles. This would allow us to keep the same configurations, but use IAM under the covers if detected that bucketpolicyonly is enabled. Just not sure how you want the changes on this the be handled, design wise.  Maybe thats a bad practice to hide that from the user. 

More reading if you are also curious in digging into this:
https://cloud.google.com/storage/docs/access-control/iam-reference
https://cloud.google.com/storage/docs/access-control/lists#default
https://cloud.google.com/storage/docs/access-control/iam#acls

**Comment by ncw** [comment]
I had a go at implementing a fix for this b9a8ec3df6a7c17e34781867340bb436ec0495b6

This introduces a new config variable bucket_policy_only.  If this is
set then rclone:
- ignores ACLs set on buckets
- ignores ACLs set on objects

I think rclone should probably be creating the bucket differently - at the moment all is does ignore the bucket ACL.

Thoughts?

https://beta.rclone.org/branch/v1.46.0-054-gb9a8ec3d-fix-3014-gcs-bucket-policy-beta/

**Comment by daltschu22** [comment]
Ive done some more testing. It seems when you invoke a server side copy, this issue is not present (on the existing stable versions of rclone). 

For example, my config being:
```
[test-perms]
type = google cloud storage
project_number = ****
service_account_file = ****
bucket_acl = private
object_acl = bucketOwnerFullControl
```
I run a copy to my first bucket. Which has normal ACL permissions enabled.

```
Access control model	
Permissions set at object-level (ACL) and bucket-level (IAM)
```

 ```
$ rclone copy -vvv ~/test/ test-perms:daltschu-test-bucket-1
2019/03/08 15:04:55 DEBUG : rclone: Version "v1.46" starting with parameters ["rclone" "copy" "-vvv" "/home/unix/daltschu/test/" "test-perms:daltschu-test-bucket-1"]
*******snipped*******
Transferred:        4.419k / 4.419 kBytes, 100%, 9.753 kBytes/s, ETA 0s
Errors:                 0
Checks:                 0 / 0, -
Transferred:            3 / 3, 100%
Elapsed time:       400ms
```

Then, copy over to the bucket that has the bucket wide permissions enabled:
```
Access control model	
Permissions set uniformly via bucket-level IAM (Bucket Policy Only)
```

```
 $ rclone copy -vvv test-perms:daltschu-test-bucket-1 test-perms:daltschu-test-bucket-2
2019/03/08 15:09:26 DEBUG : rclone: Version "v1.46" starting with parameters ["rclone" "copy" "-vvv" "test-perms:daltschu-test-bucket-1" "test-perms:daltschu-test-bucket-2"]
******snipped******
2019/03/08 15:09:27 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            3 / 3, 100%
Elapsed time:       800ms
```
No problem. So this seems to be an insert issue and not a copy issue. 

During my testing I did notice something strange, im still confirming but it seems the storage class is not respected for objects differing from the bucket storage class.
Not sure if this is intentional or not.
GCS has the option of defining a storage class per object (Even if the bucket is a different default class).
It would be excellent if support for individual object classes existed. I can open a feature request if thats something you think would be doable?

Thanks so much! (Ive moved multiple petabytes with rclone, so many thanks for your amazing work)

**Comment by ncw** [comment]
I've merged the bucket policy only fix to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.47

> Ive done some more testing. It seems when you invoke a server side copy, this issue is not present (on the existing stable versions of rclone).

That is probably what I'd expect as rclone doesn't override any of the metadata.

> During my testing I did notice something strange, im still confirming but it seems the storage class is not respected for objects differing from the bucket storage class.

Did you mean with a server side copy or a fresh insert?

The server side copy code doesn't set any flags, so will do what ever the default is.

I would have thought if you set --gcs-object-acl differently to that of the bucket then it would respect it.

> GCS has the option of defining a storage class per object (Even if the bucket is a different default class).
> It would be excellent if support for individual object classes existed. I can open a feature request if thats something you think would be doable?

Does `--gcs-object-acl` do what you want? I think that should work for uploading an object with a different ACL.

**Comment by daltschu22** [comment]
>I've merged the bucket policy only fix to master now which means it will be in the latest beta in 15-30 >mins and released in v1.47

Thats awesome! Much appreciated!

>Did you mean with a server side copy or a fresh insert?
>The server side copy code doesn't set any flags, so will do what ever the default is.
>I would have thought if you set --gcs-object-acl differently to that of the bucket then it would respect

Apologies, I should have been more clear on this. The issue im describing here is entirely separate from the original issue. 
What im seeing is during non server side copies, so new object inserts. The StorageClass, not the ACL is not getting applied. So for example, I could have a bucket with a default of `StorageClass = REGIONAL`, but I want to upload a series of files into the bucket with the `StorageClass = COLDLINE`, it seems right now you arent setting a storage class on the individual new objects, only the bucket.
So I dont believe `--gcs-object-acl` is going to do what im hoping for.

If im understanding the code right, you dont set the StorageClass in the objects metadata
```
	object := storage.Object{
		Bucket:      o.fs.bucket,
		Name:        o.fs.root + o.remote,
		ContentType: fs.MimeType(src),
		Updated:     modTime.Format(timeFormatOut), // Doesn't get set
		Metadata:    metadataFromModTime(modTime),
	}
```

GCS supports the option of setting an individual object storage class, different from the bucket class default. So I could have half my objects be Regional, and half Nearline in the same bucket for example.
Or my buckets default could be set to Regional, but I decide to upload any new objects as Coldline.
This is described here:
https://cloud.google.com/storage/docs/per-object-storage-class
https://cloud.google.com/storage/docs/storage-classes#bucket_vs_object_storage_class
The reason for this is generally so people can do tiering within the bucket.

The metadata field for that is:
```
    // StorageClass: Storage class of the object.
    StorageClass string `json:"storageClass,omitempty"`
```

I wonder if there should be another option added called `object_storage_class` to distinguish it from the bucket storage class? Either that, or just go about setting the objects storage class individually based on the existing `storage_class` configuration setting. 

Thanks!

**Comment by ncw** [comment]
> Apologies, I should have been more clear on this. The issue im describing here is entirely separate from the original issue.

Ah I see - great explanation.

> I wonder if there should be another option added called object_storage_class to distinguish it from the bucket storage class?

That would be easy enough to do, then you could set `--gcs-object-storage-class` when you wanted to do something different to what is set on the bucket.

> Either that, or just go about setting the objects storage class individually based on the existing storage_class configuration setting.

That would be easy enough too.

I think the first idea is probably the most flexible, but I wonder whether it is overkill?

Can you make a new issue about this please then we can discuss further - thanks :-)

**Comment by viyh** [comment]
Hey,

I've grabbed the beta version referenced above (and tried with the latest beta as well), and I've set `bucket_policy_only = true` in my config (as well as trying via the env var), but I'm still getting the error as soon as I enable bucket only policies on a GCS bucket: 

```
2019/04/05 16:48:10 ERROR : <XXXX/objectname>: Failed to copy: googleapi: Error 400: Cannot use ACL API to set object policy when object policies are disabled., invalid
2019/04/05 16:48:11 ERROR : <XXXX/objectname>: Failed to copy: googleapi: Error 400: Cannot use ACL API to set object policy when object policies are disabled., invalid
```

Any ideas?

Config:

```
[src]
type = sftp
host = XXX.com
user = USER
pass = PASS
use_insecure_cipher = false

[dst]
type = google cloud storage
bucket_policy_only = true
service_account_file = /config/key.json
```
