### ISSUE TITLE
--max-transfers working with server-side copying?

### ISSUE THREAD

**Issue by Qwatuz** [ncw/rclone#3033]
Currently as far as I am aware, `--max-transfers` does not work with server-side copying as the copies are done server-side.

Is it possible to allow server-side copies to acknowledge this flag?

Reason for this is to avoid rclone sitting on the 'transferring' status while it is not able to do anything.

**Comment by ncw** [comment]
> Currently as far as I am aware, `--max-transfers` does not work with server-side copying as the copies are done server-side.

That is correct.  Rclone only counts transfers for things it had to upload or download.

> Is it possible to allow server-side copies to acknowledge this flag?

Possibly...

> Reason for this is to avoid rclone sitting on the 'transferring' status while it is not able to do anything.

I'm not sure I understand what you mean here?  Can you elaborate?

**Comment by Qwatuz** [comment]
Thanks for the reply.

When the limit of server-side copies has been met it won't display any kind of error stating this, instead it will just hang on the transfer (as it cannot complete, and does not error out).

This results in the rclone transfer displaying this:

`Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            0 / 1, 0%
Elapsed time:       25.4s
Transferring:
 * Test File S01E01 …ip DD5.1 x264-VLAD.mkv: transferring
`

If it was a non-server-side copy and the download quota of the file/drive had been met, the file(s) would give the normal 403 exceeded when trying to download, and rclone would move onto the next file.


I'm unsure if rclone counts or reads the file size when doing a server-side copy, if it does then it might hopefully be an easy change if you'd be willing.

**Comment by ncw** [comment]
> When the limit of server-side copies has been met it won't display any kind of error stating this, instead it will just hang on the transfer (as it cannot complete, and does not error out).

That is strange, I would have thought it would give an error.

Maybe rclone is doing low level retries and it just takes a long time before giving an error?

**Comment by Qwatuz** [comment]
I have never seen it error out when left on over night, this is the most information it gave with -vvvvv

```
2019/03/11 20:48:51 DEBUG : pacer: Rate limited, sleeping for 16.610442837s (27 consecutive low level retries)
2019/03/11 20:48:51 DEBUG : pacer: low level retry 7/10 (error googleapi: Error 403: User rate limit exceeded., userRateLimitExceeded)
2019/03/11 20:49:08 DEBUG : pacer: Rate limited, sleeping for 16.371174355s (28 consecutive low level retries)
2019/03/11 20:49:08 DEBUG : pacer: low level retry 8/10 (error googleapi: Error 403: User rate limit exceeded., userRateLimitExceeded)
2019/03/11 20:49:24 DEBUG : pacer: Rate limited, sleeping for 16.259040582s (29 consecutive low level retries)
2019/03/11 20:49:24 DEBUG : pacer: low level retry 9/10 (error googleapi: Error 403: User rate limit exceeded., userRateLimitExceeded)
2019/03/11 20:49:40 DEBUG : pacer: Rate limited, sleeping for 16.967006727s (30 consecutive low level retries)
2019/03/11 20:49:40 DEBUG : pacer: low level retry 10/10 (error googleapi: Error 403: User rate limit exceeded., userRateLimitExceeded)
2019/03/11 20:49:40 DEBUG : Test File  S01E01 2160p WEBRip DD5.1 x264-VLAD.mkv: Received error: googleapi: Error 403: User rate limit exceeded., userRateLimitExceeded - low level retry 3/10
2019/03/11 20:49:48 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            0 / 1, 0%
Elapsed time:      7m3.9s
Transferring:
 * Test File  S01E01 …ip DD5.1 x264-VLAD.mkv: transferring

2019/03/11 20:49:57 DEBUG : pacer: Rate limited, sleeping for 16.002906594s (31 consecutive low level retries)
2019/03/11 20:49:57 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: User rate limit exceeded., userRateLimitExceeded)
2019/03/11 20:50:13 DEBUG : pacer: Rate limited, sleeping for 16.616209308s (32 consecutive low level retries)
2019/03/11 20:50:13 DEBUG : pacer: low level retry 2/10 (error googleapi: Error 403: User rate limit exceeded., userRateLimitExceeded)
2019/03/11 20:50:29 DEBUG : pacer: Rate limited, sleeping for 16.557868507s (33 consecutive low level retries)
2019/03/11 20:50:29 DEBUG : pacer: low level retry 3/10 (error googleapi: Error 403: User rate limit exceeded., userRateLimitExceeded)
2019/03/11 20:50:46 DEBUG : pacer: Rate limited, sleeping for 16.688592014s (34 consecutive low level retries)
2019/03/11 20:50:46 DEBUG : pacer: low level retry 4/10 (error googleapi: Error 403: User rate limit exceeded., userRateLimitExceeded)
2019/03/11 20:50:48 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            0 / 1, 0%
Elapsed time:      8m3.9s
Transferring:
 * Test File  S01E01 …ip DD5.1 x264-VLAD.mkv: transferring

2019/03/11 20:51:02 DEBUG : pacer: Rate limited, sleeping for 16.490263027s (35 consecutive low level retries)
2019/03/11 20:51:02 DEBUG : pacer: low level retry 5/10 (error googleapi: Error 403: User rate limit exceeded., userRateLimitExceeded)
```

**Comment by animosity22** [comment]
You seem to be generating way too many 403s. Are you using your own key and what is the command you are running?

**Comment by Qwatuz** [comment]
> 
> 
> You seem to be generating way too many 403s. Are you using your own key and what is the command you are running?

Yeah I use my own key and it was just a normal copy but with 50 transfers.

**Comment by animosity22** [comment]
Google can only create ~3 files per second and 10 transactions per second so 50 transfers make things super slow with all those retries.  Unrelated to this, you should really turn that very much down to make the 403s go away as that will speed up your overall progress.

**Comment by Qwatuz** [comment]
> 
> 
> Google can only create ~3 files per second and 10 transactions per second so 50 transfers make things super slow with all those retries. Unrelated to this, you should really turn that very much down to make the 403s go away as that will speed up your overall progress.

That's true. I usually run with just 10 although I don't much mind any 403s since I am looking for some kind of quota error I can use.

**Comment by animosity22** [comment]
The point being the more 403s you get, the more waste you have and less efficient the overall transfers are as they retry and have to sleep inbetween retries.

Worse case, a file transfer fails 10 times and errors out and you have re-run the process to copy the missed file that errored out.

**Comment by ncw** [comment]
I had a go at this here:

https://beta.rclone.org/branch/v1.46.0-103-gc3aab713-fix-3033-copy-transfer-beta/ (uploaded in 15-30 mins)

Take a look at the stats while it is running - do they look sensible?

I probably need to do the same thing for `rclone move` too.

**Comment by lex8888** [comment]
Tested with rclone copy --max-transfer 100G --drive-service-account-file and works nicely, thank you ncw!

**Comment by Qwatuz** [comment]
Wow fantastic work @ncw that works perfectly! Thanks a lot! :smiley:

**Comment by MLZC** [comment]
```
rclone v1.46.0-103-gc3aab713-fix-3033-copy-transfer-beta
- os/arch: linux/amd64
- go version: go1.12.1
```

I had the same problem. 

>rclone copy -vv --max-transfer 100G  gdcpcc:极客时间 gdcpcc:/教学视频/极客时间/

```
2019/03/24 16:35:34 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=648175448840, userRateLimitExceeded)
2019/03/24 16:35:34 DEBUG : pacer: Rate limited, increasing sleep to 1.76860607s
2019/03/24 16:35:34 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=648175448840, userRateLimitExceeded)
2019/03/24 16:35:34 DEBUG : pacer: Rate limited, increasing sleep to 2.414191499s
2019/03/24 16:35:34 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=648175448840, userRateLimitExceeded)
2019/03/24 16:35:34 DEBUG : pacer: Rate limited, increasing sleep to 4.293379135s
2019/03/24 16:35:34 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=648175448840, userRateLimitExceeded)
2019/03/24 16:35:34 DEBUG : pacer: Rate limited, increasing sleep to 8.384525304s
2019/03/24 16:35:34 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=648175448840, userRateLimitExceeded)
2019/03/24 16:35:34 DEBUG : pacer: Rate limited, increasing sleep to 16.709197636s
2019/03/24 16:35:34 DEBUG : pacer: low level retry 2/10 (error googleapi: Error 403: User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=648175448840, userRateLimitExceeded)
2019/03/24 16:35:34 DEBUG : pacer: Rate limited, increasing sleep to 16.294843511s
2019/03/24 16:35:36 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第21期_微信小程序/周二直播视频.mp4: Size and modification time the same (differ by 0s, within tolerance 1ms)
2019/03/24 16:35:36 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第21期_微信小程序/周二直播视频.mp4: Unchanged skipping
2019/03/24 16:35:36 DEBUG : pacer: Reducing sleep to 0s
2019/03/24 16:35:37 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=648175448840, userRateLimitExceeded)
2019/03/24 16:35:37 DEBUG : pacer: Rate limited, increasing sleep to 1.044349049s
2019/03/24 16:35:37 DEBUG : pacer: Reducing sleep to 0s
2019/03/24 16:35:37 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第20期_阙杭宁/CUT1.flv: Size and modification time the same (differ by 0s, within tolerance 1ms)
2019/03/24 16:35:37 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第20期_阙杭宁/CUT1.flv: Unchanged skipping
2019/03/24 16:35:37 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第20期_阙杭宁/CUT2.flv: Size and modification time the same (differ by 0s, within tolerance 1ms)
2019/03/24 16:35:37 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第20期_阙杭宁/CUT2.flv: Unchanged skipping
2019/03/24 16:35:37 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第25期_辩论赛/397309 2016-10-21 20_22_21.flv: Size and modification time the same (differ by 0s, within tolerance 1ms)
2019/03/24 16:35:37 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第25期_辩论赛/397309 2016-10-21 20_22_21.flv: Unchanged skipping
2019/03/24 16:35:37 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第23期_覃超VR直播/覃超-2016-10-07 .wmv: Size and modification time the same (differ by 0s, within tolerance 1ms)
2019/03/24 16:35:37 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第23期_覃超VR直播/覃超-2016-10-07 .wmv: Unchanged skipping
2019/03/24 16:35:46 INFO  : 
Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:              3050 / 3050, 100%
Transferred:            0 / 1, 0%
Elapsed time:      1m1.7s
Transferring:
 * 极客时间-已经完结的课程/11 大咖说/In…16期 续彬/InfoQ大咖说-续彬.m4v: transferring

2019/03/24 16:35:53 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第27期_刘相/397309 2016-10-27 20_16_32.flv: Size and modification time the same (differ by 0s, within tolerance 1ms)
2019/03/24 16:35:53 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第27期_刘相/397309 2016-10-27 20_16_32.flv: Unchanged skipping
2019/03/24 16:35:53 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第27期_刘相/397309 2016-10-27 21_36_08.flv: Size and modification time the same (differ by 0s, within tolerance 1ms)
2019/03/24 16:35:53 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第27期_刘相/397309 2016-10-27 21_36_08.flv: Unchanged skipping
2019/03/24 16:35:53 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第27期_刘相/397309 2016-10-27 21_36_23.flv: Size and modification time the same (differ by 0s, within tolerance 1ms)
2019/03/24 16:35:53 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第27期_刘相/397309 2016-10-27 21_36_23.flv: Unchanged skipping
2019/03/24 16:35:53 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第27期_刘相/397309 2016-10-27 21_36_54.flv: Size and modification time the same (differ by 0s, within tolerance 1ms)
2019/03/24 16:35:53 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第27期_刘相/397309 2016-10-27 21_36_54.flv: Unchanged skipping
2019/03/24 16:35:53 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第27期_刘相/397309 2016-10-27 21_37_41.flv: Size and modification time the same (differ by 0s, within tolerance 1ms)
2019/03/24 16:35:53 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第27期_刘相/397309 2016-10-27 21_37_41.flv: Unchanged skipping
2019/03/24 16:35:53 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第59期张真/VideoJoiner170811001439.mp4: Size and modification time the same (differ by 0s, within tolerance 1ms)
2019/03/24 16:35:53 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第59期张真/VideoJoiner170811001439.mp4: Unchanged skipping
2019/03/24 16:35:53 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第26期_1024特别直播_崔宝秋/397309 2016-10-24 20_27_24.flv: Size and modification time the same (differ by 0s, within tolerance 1ms)
2019/03/24 16:35:53 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第26期_1024特别直播_崔宝秋/397309 2016-10-24 20_27_24.flv: Unchanged skipping
2019/03/24 16:35:53 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第28期_肖德时/397309 2016-11-03 20_16_59.flv: Size and modification time the same (differ by 0s, within tolerance 1ms)
2019/03/24 16:35:53 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第28期_肖德时/397309 2016-11-03 20_16_59.flv: Unchanged skipping
2019/03/24 16:35:53 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第60期李道兵/VideoJoiner170817234520.mp4: Size and modification time the same (differ by 0s, within tolerance 1ms)
2019/03/24 16:35:53 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第60期李道兵/VideoJoiner170817234520.mp4: Unchanged skipping
2019/03/24 16:35:53 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ 大咖说第9期 鲁航/另一版本备份/397309 2016-07-07 20_13_21.flv: Size and modification time the same (differ by 0s, within tolerance 1ms)
2019/03/24 16:35:53 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ 大咖说第9期 鲁航/另一版本备份/397309 2016-07-07 20_13_21.flv: Unchanged skipping
2019/03/24 16:35:53 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ 大咖说第9期 鲁航/另一版本备份/397309 2016-07-07 20_30_37.flv: Size and modification time the same (differ by 0s, within tolerance 1ms)
2019/03/24 16:35:53 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ 大咖说第9期 鲁航/另一版本备份/397309 2016-07-07 20_30_37.flv: Unchanged skipping
2019/03/24 16:35:53 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第56期-康德胜/VideoJoiner170629235728.mp4: Size and modification time the same (differ by 0s, within tolerance 1ms)
2019/03/24 16:35:53 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第56期-康德胜/VideoJoiner170629235728.mp4: Unchanged skipping
2019/03/24 16:35:53 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第58期郑泽宇/VideoJoiner170720235020.mp4: Size and modification time the same (differ by 0s, within tolerance 1ms)
2019/03/24 16:35:53 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第58期郑泽宇/VideoJoiner170720235020.mp4: Unchanged skipping
2019/03/24 16:35:53 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=648175448840, userRateLimitExceeded)
2019/03/24 16:35:53 DEBUG : pacer: Rate limited, increasing sleep to 1.914701606s
2019/03/24 16:35:53 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=648175448840, userRateLimitExceeded)
2019/03/24 16:35:53 DEBUG : pacer: Rate limited, increasing sleep to 1.162096745s
2019/03/24 16:35:53 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=648175448840, userRateLimitExceeded)
2019/03/24 16:35:53 DEBUG : pacer: Rate limited, increasing sleep to 2.416090587s
2019/03/24 16:35:53 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=648175448840, userRateLimitExceeded)
2019/03/24 16:35:53 DEBUG : pacer: Rate limited, increasing sleep to 2.596237875s
2019/03/24 16:35:53 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=648175448840, userRateLimitExceeded)
2019/03/24 16:35:53 DEBUG : pacer: Rate limited, increasing sleep to 4.644502472s
2019/03/24 16:35:53 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=648175448840, userRateLimitExceeded)
2019/03/24 16:35:53 DEBUG : pacer: Rate limited, increasing sleep to 4.193893265s
2019/03/24 16:35:53 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=648175448840, userRateLimitExceeded)
2019/03/24 16:35:53 DEBUG : pacer: Rate limited, increasing sleep to 8.291529455s
2019/03/24 16:35:53 DEBUG : pacer: low level retry 2/10 (error googleapi: Error 403: User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=648175448840, userRateLimitExceeded)
2019/03/24 16:35:53 DEBUG : pacer: Rate limited, increasing sleep to 16.43627512s
2019/03/24 16:35:53 DEBUG : pacer: low level retry 2/10 (error googleapi: Error 403: User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=648175448840, userRateLimitExceeded)
2019/03/24 16:35:53 DEBUG : pacer: Rate limited, increasing sleep to 8.413677534s
2019/03/24 16:35:53 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=648175448840, userRateLimitExceeded)
2019/03/24 16:35:53 DEBUG : pacer: Rate limited, increasing sleep to 16.692884784s
2019/03/24 16:35:53 DEBUG : pacer: Reducing sleep to 0s
2019/03/24 16:35:53 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第61期李汐/VideoJoiner170825000700.mp4: Size and modification time the same (differ by 0s, within tolerance 1ms)
2019/03/24 16:35:53 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第61期李汐/VideoJoiner170825000700.mp4: Unchanged skipping
2019/03/24 16:35:53 DEBUG : pacer: Reducing sleep to 0s
2019/03/24 16:35:55 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第63期史海峰/VideoJoiner170914232858.mp4: Size and modification time the same (differ by 0s, within tolerance 1ms)
2019/03/24 16:35:55 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第63期史海峰/VideoJoiner170914232858.mp4: Unchanged skipping
2019/03/24 16:35:55 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第66期张轩健张思远/1104.mp4: Size and modification time the same (differ by 0s, within tolerance 1ms)
2019/03/24 16:35:55 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第66期张轩健张思远/1104.mp4: Unchanged skipping
2019/03/24 16:35:55 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第62期程显峰/VideoJoiner170901142659.mp4: Size and modification time the same (differ by 0s, within tolerance 1ms)
2019/03/24 16:35:55 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第62期程显峰/VideoJoiner170901142659.mp4: Unchanged skipping
2019/03/24 16:35:55 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第65期刘少山/VideoJoiner171027205800.mp4: Size and modification time the same (differ by 0s, within tolerance 1ms)
2019/03/24 16:35:55 DEBUG : 极客时间-已经完结的课程/11 大咖说/InfoQ大咖说第65期刘少山/VideoJoiner171027205800.mp4: Unchanged skipping
2019/03/24 16:35:55 DEBUG : 极客时间-已经完结的课程/11 大咖说/MacBook发布会_覃超/397309 2016-10-28 01_36_07.flv: Size and modification time the same (differ by 0s, within tolerance 1ms)
2019/03/24 16:35:55 DEBUG : 极客时间-已经完结的课程/11 大咖说/MacBook发布会_覃超/397309 2016-10-28 01_36_07.flv: Unchanged skipping
2019/03/24 16:35:55 DEBUG : 极客时间-已经完结的课程/11 大咖说/MacBook发布会_覃超/397309 2016-10-28 01_42_18.flv: Size and modification time the same (differ by 0s, within tolerance 1ms)
2019/03/24 16:35:55 DEBUG : 极客时间-已经完结的课程/11 大咖说/MacBook发布会_覃超/397309 2016-10-28 01_42_18.flv: Unchanged skipping
2019/03/24 16:35:55 DEBUG : 极客时间-已经完结的课程/11 大咖说/MacBook发布会_覃超/397309 2016-10-28 01_43_16.flv: Size and modification time the same (differ by 0s, within tolerance 1ms)
2019/03/24 16:35:55 DEBUG : 极客时间-已经完结的课程/11 大咖说/MacBook发布会_覃超/397309 2016-10-28 01_43_16.flv: Unchanged skipping
2019/03/24 16:35:55 DEBUG : 极客时间-已经完结的课程/11 大咖说/MacBook发布会_覃超/397309 2016-10-28 02_48_09.flv: Size and modification time the same (differ by 0s, within tolerance 1ms)
2019/03/24 16:35:55 DEBUG : 极客时间-已经完结的课程/11 大咖说/MacBook发布会_覃超/397309 2016-10-28 02_48_09.flv: Unchanged skipping
2019/03/24 16:35:55 DEBUG : 极客时间-已经完结的课程/11 大咖说/MacBook发布会_覃超/397309 2016-10-28 03_37_00.flv: Size and modification time the same (differ by 0s, within tolerance 1ms)
2019/03/24 16:35:55 DEBUG : 极客时间-已经完结的课程/11 大咖说/MacBook发布会_覃超/397309 2016-10-28 03_37_00.flv: Unchanged skipping
2019/03/24 16:35:55 INFO  : Google drive root '教学视频/极客时间': Waiting for checks to finish
2019/03/24 16:35:55 INFO  : Google drive root '教学视频/极客时间': Waiting for transfers to finish
2019/03/24 16:36:46 INFO  : 
Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:              3073 / 3073, 100%
Transferred:            0 / 1, 0%
Elapsed time:      2m1.7s
Transferring:
 * 极客时间-已经完结的课程/11 大咖说/In…16期 续彬/InfoQ大咖说-续彬.m4v: transferring

2019/03/24 16:37:06 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 500: Internal Error, internalError)
2019/03/24 16:37:06 DEBUG : pacer: Rate limited, increasing sleep to 1.62219741s
2019/03/24 16:37:46 INFO  : 
Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:              3073 / 3073, 100%
Transferred:            0 / 1, 0%
Elapsed time:      3m1.7s
Transferring:
 * 极客时间-已经完结的课程/11 大咖说/In…16期 续彬/InfoQ大咖说-续彬.m4v: transferring
```

**Comment by Qwatuz** [comment]
I have noticed some files will not server-side copy and don't appear to have any errors, they just hang.

This can cause issues with the newly updated `--max-transfer` flag as the transfer limit is met it will cancel transfers except for the ones hanging - so rclone will still remain on "transferring" as posted above for those bugged ones.

I'm not sure if when the max transfers is met, is rclone meant to stop future transfers or end the entire transfer including ones in progress?

**Comment by MLZC** [comment]
when the max transfers is met, rclone is the same as before.

I have a 45G file. So I tried using the following command. 
 
 >rclone copy --max-transfer 30G -vv gdswccd:SHE gdswccd:test

```
2019/03/25 08:23:42 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 8 / 8, 100%
Transferred:            0 / 1, 0%
Elapsed time:      1m7.5s
Transferring:
 * S H E-2gether 4ever En…BDMV/STREAM/00000.m2ts: transferring

2019/03/25 08:24:33 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 500: Internal Error, internalError)
2019/03/25 08:24:33 DEBUG : pacer: Rate limited, increasing sleep to 1.124854051s
2019/03/25 08:24:42 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 8 / 8, 100%
Transferred:            0 / 1, 0%
Elapsed time:      2m7.5s
Transferring:
 * S H E-2gether 4ever En…BDMV/STREAM/00000.m2ts: transferring

2019/03/25 08:25:42 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 8 / 8, 100%
Transferred:            0 / 1, 0%
Elapsed time:      3m7.5s
Transferring:
 * S H E-2gether 4ever En…BDMV/STREAM/00000.m2ts: transferring

2019/03/25 08:26:02 DEBUG : pacer: low level retry 2/10 (error googleapi: Error 500: Internal Error, internalError)
2019/03/25 08:26:02 DEBUG : pacer: Rate limited, increasing sleep to 2.839163904s
2019/03/25 08:26:03 DEBUG : pacer: low level retry 3/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2019/03/25 08:26:03 DEBUG : pacer: Rate limited, increasing sleep to 4.476405668s
2019/03/25 08:26:06 DEBUG : pacer: low level retry 4/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2019/03/25 08:26:06 DEBUG : pacer: Rate limited, increasing sleep to 8.314632984s
2019/03/25 08:26:42 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 8 / 8, 100%
Transferred:            0 / 1, 0%
Elapsed time:      4m7.5s
Transferring:
 * S H E-2gether 4ever En…BDMV/STREAM/00000.m2ts: transferring

2019/03/25 08:27:40 DEBUG : pacer: low level retry 5/10 (error googleapi: Error 500: Internal Error, internalError)
2019/03/25 08:27:40 DEBUG : pacer: Rate limited, increasing sleep to 16.479871959s
2019/03/25 08:27:42 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 8 / 8, 100%
Transferred:            0 / 1, 0%
Elapsed time:      5m7.5s
Transferring:
 * S H E-2gether 4ever En…BDMV/STREAM/00000.m2ts: transferring
```

>rclone copy -vv  gdswccd:SHE gdswccd:test

```
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 8 / 8, 100%
Transferred:            0 / 1, 0%
Elapsed time:     1m11.5s
Transferring:
 * S H E-2gether 4ever En…BDMV/STREAM/00000.m2ts: transferring

2019/03/25 08:33:05 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 8 / 8, 100%
Transferred:            0 / 1, 0%
Elapsed time:     2m11.5s
Transferring:
 * S H E-2gether 4ever En…BDMV/STREAM/00000.m2ts: transferring

2019/03/25 08:33:11 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 500: Internal Error, internalError)
2019/03/25 08:33:11 DEBUG : pacer: Rate limited, increasing sleep to 1.115930171s
2019/03/25 08:34:05 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 8 / 8, 100%
Transferred:            0 / 1, 0%
Elapsed time:     3m11.5s
Transferring:
 * S H E-2gether 4ever En…BDMV/STREAM/00000.m2ts: transferring
```

**Comment by lex8888** [comment]
@ncw Few bugs to work out, but this has saved enormous amounts of manual wait time, thank you.

The files that appear to hang (for me and a few others who are testing) are all ones with 4 letter extensions. Example are .mk3d, .m2ts and similar.

That said this is very useful and stable. Do you plan to add the feature into upcoming beta releases? Assuming you have not already done ;-)

**Comment by Qwatuz** [comment]
> 
> 
> @ncw Few bugs to work out, but this has saved enormous amounts of manual wait time, thank you.
> 
> The files that appear to hang (for me and a few others who are testing) are all ones with 4 letter extensions. Example are .mk3d, .m2ts and similar.
> 
> That said this is very useful and stable. Do you plan to add the feature into upcoming beta releases? Assuming you have not already done ;-)

Very interesting, I recall most of the files being .mk3d that failed to copy.

**Comment by ncw** [comment]
> I'm not sure if when the max transfers is met, is rclone meant to stop future transfers or end the entire transfer including ones in progress (bugged or not)?

Rclone doesn't cancel the transfer in progress.  In fact I'm not sure if it could since rclone just asks google to do the transfer and waits for it to complete.



> That said this is very useful and stable. Do you plan to add the feature into upcoming beta releases? Assuming you have not already done ;-)

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.47

I'll leave this open for a bit to see if we can improve the hanging situation.

**Comment by lex8888** [comment]
@ncw  thank you for the amazingly quick fixes and commits. I am always astonished at how fast you are able to find the source of an issue and rectify it.

I've been running this beta in quite a few situations. The hang in Drive only occurs when the 'residual' files still being transferred are larger in size than the difference between 750G and --max-transfer (as I described above). The transfer continues after hitting --max-transfer with files that were already copying, but hangs when the transfer hits 750G (as it is supposed to do).  

I'm working around it by setting --max-transfer < (750G - (# of transfers X avg file size)) and adding a failsafe timeout as well.

**Comment by Qwatuz** [comment]
> 
> 
> @ncw thank you for the amazingly quick fixes and commits. I am always astonished at how fast you are able to find the source of an issue and rectify it.
> 
> I've been running this beta in quite a few situations. The hang in Drive only occurs when the 'residual' files still being transferred are larger in size than the difference between 750G and --max-transfer (as I described above). The transfer continues after hitting --max-transfer with files that were already copying, but hangs when the transfer hits 750G (as it is supposed to do).
> 
> I'm working around it by setting --max-transfer < (750G - (# of transfers X avg file size)) and adding a failsafe timeout as well.

Are you finding that the 4 digit extensions aren't the cause?

**Comment by lex8888** [comment]
@Qwatuz yes, the 4 character extensions like m2ts and mk3d are still hanging. It happens as well with manual copy/sync so doesn't seem connected with --max-transfer.

I do a sweep-sync periodically with --disable move,copy and it picks up the m2ts/mk3d/etc files.

@ncw I don't see a beta 1.47 yet but it seems to be working in beta 1.46.0-109

**Comment by ncw** [comment]
> @Qwatuz yes, the 4 character extensions like m2ts and mk3d are still hanging. It happens as well with manual copy/sync so doesn't seem connected with --max-transfer.

That is very strange!

Do you think it might be google indexing the video files?
 
> I do a sweep-sync periodically with --disable move,copy and it picks up the m2ts/mk3d/etc files.
> 
> @ncw I don't see a beta 1.47 yet but it seems to be working in beta 1.46.0-109

1.47 isn't out yet - the latest beta is [here](https://beta.rclone.org)

**Comment by Qwatuz** [comment]
> 
> 
> > @Qwatuz yes, the 4 character extensions like m2ts and mk3d are still hanging. It happens as well with manual copy/sync so doesn't seem connected with --max-transfer.
> 
> That is very strange!

It may be as I can server-side copy `test.1234` fine.

**Comment by 88lex** [comment]
@ncw Returning to the 'hang' issue that I mentioned above:
When rclone hits the --max-transfer limit and continues to sync the files that are in the queue it will normally complete and exit nicely as long as the remaining files in the queue (shown below the process info) are able to complete syncing before hitting the 'hard limit' that Google enforces (either 750G or less if some of the limit has already been used).

However, if rclone hits the hard limiit it hangs with sync (but not with copy).  I am guessing this could be related to rclone sync trying to delete files at the end of the sync.  This guess driven by experimenting with using --delete-before / --delete-during which so far appear to be helping to avoid the hang state.  Perhaps something is blocking a clean exit when the default --delete-after is enabled?

Just a guess. But maybe something to take a look at when you have a moment.  Kind regards

**Comment by ncw** [comment]
@88lex if you run the transfer with `-vv` does it count up timeouts and or low-level retries when it is hanging?

One thing you could do is kill the process when it has hung with SIGQUIT, so either press `CTRL-\` or run `kill -QUIT 1234` where 1234 is the PID of rclone from `ps ax`.  That will print a lot of stuff which will tell us exactly what rclone is doing at that point.

**Comment by ncw** [comment]
I believe this will be fixed by this beta - can you give it a test?

https://beta.rclone.org/branch/v1.48.0-062-g3fcd4c69-fix-3070-drive-copy-beta/ (uploaded in 15-30 mins)

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.49
