### ISSUE TITLE
rclone mount leads to DELETE when appending to a remotely locked file

### ISSUE THREAD

**Issue by wlohman-surfsara** [ncw/rclone#3263]
#### What is the problem you are having with rclone?
I've noticed that when I write (append) to a file over rclone mount in quick succession, sometimes ownCloud returns a 423 (file locked). This results in rclone giving a DELETE on the file.

#### What is your rclone version (output from `rclone version`)
rclone --version
rclone v1.47.0
- os/arch: linux/amd64
- go version: go1.11.5

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
CentOS Linux release 7.6 (64 bit)

####  Which cloud storage system are you using? (eg Google Drive)
ownCloud (10.0.10 and 10.1)

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
Mounting:
```
rclone mount -vvv --debug-fuse --vfs-cache-mode=full owncloud:/ /mnt/rclone/ 2>&1|tee /tmrclone_append-full-surfdrive.log
```

Then I run:
```
time for i in {1..100}
do 
    echo run $i >> /mnt/rclone/rclone_appending.txt
done
```
This works for a time, but after a while it will start erroring:
```
-bash: echo: write error: Input/output error
```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Apache logs:
```
10.255.0.3 -  [14/Jun/2019:12:06:45 +0200] "PUT /remote.php/nonshib-webdav/rclone_appending.txt HTTP/1.1" 204 - "-" "rclone/v1.47.0" microsecs:2407940 response_size:0 bytes_received:660 bytes_sent:947 XQNxtXtu9FMVBQEOlV-QkQAAAMY - 17497
10.255.0.6 -  [14/Jun/2019:12:06:47 +0200] "PROPFIND /remote.php/nonshib-webdav/rclone_appending.txt HTTP/1.1" 207 733 "-" "rclone/v1.47.0" microsecs:333823 response_size:733 bytes_received:735 bytes_sent:1647 XQNxt3tu9FMVBQEOlV-QkgAAAMY - 17497
10.255.0.2 -  [14/Jun/2019:12:06:47 +0200] "PUT /remote.php/nonshib-webdav/rclone_appending.txt HTTP/1.1" 204 - "-" "rclone/v1.47.0" microsecs:2254121 response_size:0 bytes_received:668 bytes_sent:939 XQNxt3tu9FMVBQEOlV-QkwAAAMY - 17497
10.255.0.3 -  [14/Jun/2019:12:06:50 +0200] "PROPFIND /remote.php/nonshib-webdav/rclone_appending.txt HTTP/1.1" 207 734 "-" "rclone/v1.47.0" microsecs:299133 response_size:734 bytes_received:735 bytes_sent:1656 XQNxuntu9FMVBQEOlV-QlQAAAMY - 17497
10.255.0.6 -  [14/Jun/2019:12:06:50 +0200] "PUT /remote.php/nonshib-webdav/rclone_appending.txt HTTP/1.1" 423 240 "-" "rclone/v1.47.0" microsecs:281125 response_size:240 bytes_received:675 bytes_sent:1098 XQNxuntu9FMVBQEOlV-QlgAAAMY - 17497
10.255.0.2 -  [14/Jun/2019:12:06:51 +0200] "DELETE /remote.php/nonshib-webdav/rclone_appending.txt HTTP/1.1" 204 - "-" "rclone/v1.47.0" microsecs:1952813 response_size:0 bytes_received:415 bytes_sent:843 XQNxu3tu9FMVBQEOlV-QmAAAAME - 17497
10.255.0.3 -  [14/Jun/2019:12:06:53 +0200] "GET /remote.php/nonshib-webdav/rclone_appending.txt HTTP/1.1" 404 248 "-" "rclone/v1.47.0" microsecs:265505 response_size:248 bytes_received:412 bytes_sent:1109 XQNxvXtu9FMVBQEOlV-QmQAAAME - 17497
```

The owncloud log itself gives some more detail (though not more information):
```
{
  "reqId": "XQNxuntu9FMVBQEOlV-QlgAAAMY",
  "level": 1,
  "time": "14/Jun/2019:12:06:50",
  "remoteAddr": "10.234.1.10",
  "user": "wybrandl",
  "app": "admin_audit",
  "method": "PUT",
  "url": "/remote.php/nonshib-webdav/rclone_appending.txt",
  "message": "User wybrandl logged into Miskatonic University from IP address: 10.234.1.10 [CLIENT_IP: 10.234.1.10] [USER_AGENT: rclone/v1.47.0]"
}
{
  "reqId": "XQNxuntu9FMVBQEOlV-QlgAAAMY",
  "level": 4,
  "time": "14/Jun/2019:12:06:50",
  "remoteAddr": "10.234.1.10",
  "user": "wybrandl",
  "app": "webdav",
  "method": "PUT",
  "url": "/remote.php/nonshib-webdav/rclone_appending.txt",
  "message": "Exception: HTTP/1.1 423 \"rclone_appending.txt\" is locked: {\"Exception\":\"OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Exception\\\\FileLocked\",\"Message\":\"\\\"rclone_appending.txt\\\" is locked\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/owncloud\\/lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(1130): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #143)\\n#1 \\/var\\/www\\/owncloud\\/lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->updateFile('rclone_appendin...', Resource id #143, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\/var\\/www\\/owncloud\\/lib\\/composer\\/sabre\\/event\\/lib\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\/var\\/www\\/owncloud\\/lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#5 \\/var\\/www\\/owncloud\\/lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\/var\\/www\\/owncloud\\/apps\\/dav\\/appinfo\\/v1\\/webdav.php(65): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\/var\\/www\\/owncloud\\/apps\\/user_shibboleth\\/appinfo\\/remote.php(15): require('\\/var\\/www\\/ownclo...')\\n#8 \\/var\\/www\\/owncloud\\/remote.php(165): require_once('\\/var\\/www\\/ownclo...')\\n#9 {main}\",\"File\":\"\\/var\\/www\\/owncloud\\/apps\\/dav\\/lib\\/Connector\\/Sabre\\/File.php\",\"Line\":191}"
}
```

So what seems to be happening, is that every append leads to a PUT and a PROPFIND. Then, apparently, once every so often ownCloud is not done yet with releasing the file lock, and returns a 423. And what happens next is that rclone gives a DELETE. Now the file is gone, locally and remotely. In ownCloud, you can see the file in the trashbin, and restore it from there. But locally the file stays gone, and both rclone and my loop are unable to write to it.

This is the rclone output:
```
2019/06/14 12:06:50 INFO  : rclone_appending.txt: Copied (replaced existing)
2019/06/14 12:06:50 DEBUG : rclone_appending.txt: transferred to remote
2019/06/14 12:06:50 DEBUG : rclone_appending.txt(0xc00056dda0): >close: err=<nil>
2019/06/14 12:06:50 DEBUG : &{rclone_appending.txt (rw)}: >Flush: err=<nil>
2019/06/14 12:06:50 DEBUG : fuse: -> [ID=0x52] Flush
2019/06/14 12:06:50 DEBUG : fuse: <- Open [ID=0x54 Node=0x2 Uid=0 Gid=0 Pid=5753] dir=false fl=OpenWriteOnly+OpenAppend
2019/06/14 12:06:50 DEBUG : rclone_appending.txt: Open: flags=OpenWriteOnly+OpenAppend
2019/06/14 12:06:50 DEBUG : rclone_appending.txt: Open: flags=O_WRONLY|O_APPEND
2019/06/14 12:06:50 DEBUG : rclone_appending.txt: >Open: fd=rclone_appending.txt (rw), err=<nil>
2019/06/14 12:06:50 DEBUG : rclone_appending.txt: >Open: fh=&{rclone_appending.txt (rw)}, err=<nil>
2019/06/14 12:06:50 DEBUG : fuse: -> [ID=0x54] Open 0x1 fl=0
2019/06/14 12:06:50 DEBUG : fuse: <- Release [ID=0x53 Node=0x2 Uid=0 Gid=0 Pid=0] 0x2 fl=OpenWriteOnly+OpenAppend rfl=0 owner=0x0
2019/06/14 12:06:50 DEBUG : &{rclone_appending.txt (rw)}: Release: 
2019/06/14 12:06:50 DEBUG : rclone_appending.txt(0xc00056dda0): RWFileHandle.Release nothing to do
2019/06/14 12:06:50 DEBUG : &{rclone_appending.txt (rw)}: >Release: err=<nil>
2019/06/14 12:06:50 DEBUG : fuse: -> [ID=0x53] Release
2019/06/14 12:06:50 DEBUG : fuse: <- Flush [ID=0x55 Node=0x2 Uid=0 Gid=0 Pid=5753] 0x1 fl=0x0 lk=0xd1b4980456f80000
2019/06/14 12:06:50 DEBUG : &{rclone_appending.txt (rw)}: Flush: 
2019/06/14 12:06:50 DEBUG : &{rclone_appending.txt (rw)}: >Flush: err=<nil>
2019/06/14 12:06:50 DEBUG : fuse: -> [ID=0x55] Flush
2019/06/14 12:06:50 DEBUG : fuse: <- Write [ID=0x56 Node=0x2 Uid=0 Gid=0 Pid=5753] 0x1 7 @103 fl=0 lock=0 ffl=OpenWriteOnly+OpenAppend
2019/06/14 12:06:50 DEBUG : &{rclone_appending.txt (rw)}: Write: len=7, offset=103
2019/06/14 12:06:50 DEBUG : rclone_appending.txt: Size and modification time the same (differ by 846.265491ms, within tolerance 1s)
2019/06/14 12:06:50 DEBUG : rclone_appending.txt: Unchanged skipping
2019/06/14 12:06:50 DEBUG : rclone_appending.txt(0xc00050e3c0): Opened existing cached copy with flags=O_WRONLY|O_APPEND
2019/06/14 12:06:50 DEBUG : &{rclone_appending.txt (rw)}: >Write: written=7, err=<nil>
2019/06/14 12:06:50 DEBUG : fuse: -> [ID=0x56] Write 7
2019/06/14 12:06:50 DEBUG : fuse: <- Flush [ID=0x57 Node=0x2 Uid=0 Gid=0 Pid=5753] 0x1 fl=0x0 lk=0xd1b4980456f80000
2019/06/14 12:06:50 DEBUG : &{rclone_appending.txt (rw)}: Flush: 
2019/06/14 12:06:50 DEBUG : rclone_appending.txt(0xc00050e3c0): close: 
2019/06/14 12:06:50 DEBUG : rclone_appending.txt: Sizes differ (src 110 vs dst 103)
2019/06/14 12:06:53 ERROR : rclone_appending.txt: Failed to copy: "rclone_appending.txt" is locked: OCA\DAV\Connector\Sabre\Exception\FileLocked: 423 Locked
2019/06/14 12:06:53 ERROR : rclone_appending.txt(0xc00050e3c0): failed to transfer file from cache to remote: "rclone_appending.txt" is locked: OCA\DAV\Connector\Sabre\Exception\FileLocked: 423 Locked
2019/06/14 12:06:53 DEBUG : rclone_appending.txt(0xc00050e3c0): >close: err=failed to transfer file from cache to remote: "rclone_appending.txt" is locked: OCA\DAV\Connector\Sabre\Exception\FileLocked: 423 Locked
2019/06/14 12:06:53 ERROR : rclone_appending.txt(0xc00050e3c0): RWFileHandle.Flush error: failed to transfer file from cache to remote: "rclone_appending.txt" is locked: OCA\DAV\Connector\Sabre\Exception\FileLocked: 423 Locked
2019/06/14 12:06:53 DEBUG : &{rclone_appending.txt (rw)}: >Flush: err=failed to transfer file from cache to remote: "rclone_appending.txt" is locked: OCA\DAV\Connector\Sabre\Exception\FileLocked: 423 Locked
2019/06/14 12:06:53 DEBUG : fuse: -> [ID=0x57] Flush error=EIO: failed to transfer file from cache to remote: "rclone_appending.txt" is locked: OCA\DAV\Connector\Sabre\Exception\FileLocked: 423 Locked
2019/06/14 12:06:53 DEBUG : fuse: <- Open [ID=0x59 Node=0x2 Uid=0 Gid=0 Pid=5753] dir=false fl=OpenWriteOnly+OpenAppend
2019/06/14 12:06:53 DEBUG : rclone_appending.txt: Open: flags=OpenWriteOnly+OpenAppend
2019/06/14 12:06:53 DEBUG : rclone_appending.txt: Open: flags=O_WRONLY|O_APPEND
2019/06/14 12:06:53 DEBUG : rclone_appending.txt: >Open: fd=rclone_appending.txt (rw), err=<nil>
2019/06/14 12:06:53 DEBUG : rclone_appending.txt: >Open: fh=&{rclone_appending.txt (rw)}, err=<nil>
2019/06/14 12:06:53 DEBUG : fuse: -> [ID=0x59] Open 0x2 fl=0
2019/06/14 12:06:53 DEBUG : fuse: <- Release [ID=0x58 Node=0x2 Uid=0 Gid=0 Pid=0] 0x1 fl=OpenWriteOnly+OpenAppend rfl=0 owner=0x0
2019/06/14 12:06:53 DEBUG : &{rclone_appending.txt (rw)}: Release: 
2019/06/14 12:06:53 DEBUG : rclone_appending.txt(0xc00050e3c0): RWFileHandle.Release nothing to do
2019/06/14 12:06:53 DEBUG : &{rclone_appending.txt (rw)}: >Release: err=<nil>
2019/06/14 12:06:53 DEBUG : fuse: -> [ID=0x58] Release
2019/06/14 12:06:53 DEBUG : fuse: <- Flush [ID=0x5a Node=0x2 Uid=0 Gid=0 Pid=5753] 0x2 fl=0x0 lk=0xd1b4980456f80000
2019/06/14 12:06:53 DEBUG : &{rclone_appending.txt (rw)}: Flush: 
2019/06/14 12:06:53 DEBUG : &{rclone_appending.txt (rw)}: >Flush: err=<nil>
2019/06/14 12:06:53 DEBUG : fuse: -> [ID=0x5a] Flush
2019/06/14 12:06:53 DEBUG : fuse: <- Write [ID=0x5b Node=0x2 Uid=0 Gid=0 Pid=5753] 0x2 7 @110 fl=0 lock=0 ffl=OpenWriteOnly+OpenAppend
2019/06/14 12:06:53 DEBUG : &{rclone_appending.txt (rw)}: Write: len=7, offset=110
2019/06/14 12:06:53 DEBUG : rclone_appending.txt: Sizes differ (src 103 vs dst 110)
2019/06/14 12:06:53 ERROR : rclone_appending.txt: Failed to copy: failed to open source object: File with name rclone_appending.txt could not be located: Sabre\DAV\Exception\NotFound: 404 Not Found
2019/06/14 12:06:53 DEBUG : &{rclone_appending.txt (rw)}: >Write: written=0, err=open RW handle failed to update cached file: failed to open source object: File with name rclone_appending.txt could not be located: Sabre\DAV\Exception\NotFound: 404 Not Found
2019/06/14 12:06:53 DEBUG : fuse: -> [ID=0x5b] Write error=EIO: open RW handle failed to update cached file: failed to open source object: File with name rclone_appending.txt could not be located: Sabre\DAV\Exception\NotFound: 404 Not Found
2019/06/14 12:06:53 DEBUG : fuse: <- Flush [ID=0x5c Node=0x2 Uid=0 Gid=0 Pid=5753] 0x2 fl=0x0 lk=0xd1b4980456f80000
2019/06/14 12:06:53 DEBUG : &{rclone_appending.txt (rw)}: Flush: 
2019/06/14 12:06:53 DEBUG : &{rclone_appending.txt (rw)}: >Flush: err=<nil>
2019/06/14 12:06:53 DEBUG : fuse: -> [ID=0x5c] Flush
2019/06/14 12:06:53 DEBUG : fuse: <- Open [ID=0x5e Node=0x2 Uid=0 Gid=0 Pid=5753] dir=false fl=OpenWriteOnly+OpenAppend
2019/06/14 12:06:53 DEBUG : rclone_appending.txt: Open: flags=OpenWriteOnly+OpenAppend
2019/06/14 12:06:53 DEBUG : rclone_appending.txt: Open: flags=O_WRONLY|O_APPEND
2019/06/14 12:06:53 DEBUG : rclone_appending.txt: >Open: fd=rclone_appending.txt (rw), err=<nil>
2019/06/14 12:06:53 DEBUG : rclone_appending.txt: >Open: fh=&{rclone_appending.txt (rw)}, err=<nil>
2019/06/14 12:06:53 DEBUG : fuse: -> [ID=0x5e] Open 0x1 fl=0
2019/06/14 12:06:53 DEBUG : fuse: <- Release [ID=0x5d Node=0x2 Uid=0 Gid=0 Pid=0] 0x2 fl=OpenWriteOnly+OpenAppend rfl=0 owner=0x0
2019/06/14 12:06:53 DEBUG : &{rclone_appending.txt (rw)}: Release: 
2019/06/14 12:06:53 DEBUG : rclone_appending.txt(0xc00050ea80): RWFileHandle.Release closing
2019/06/14 12:06:53 DEBUG : rclone_appending.txt(0xc00050ea80): close: 
2019/06/14 12:06:53 DEBUG : rclone_appending.txt(0xc00050ea80): not modified so not transferring
2019/06/14 12:06:53 DEBUG : rclone_appending.txt(0xc00050ea80): >close: err=<nil>
```

**Comment by ncw** [comment]
What is happening here I think is
- the upload fails with a 423 error - this is when the webdav backend deletes the file
```
2019/06/14 12:06:50 DEBUG : rclone_appending.txt: Sizes differ (src 110 vs dst 103)
2019/06/14 12:06:53 ERROR : rclone_appending.txt: Failed to copy: "rclone_appending.txt" is locked: OCA\DAV\Connector\Sabre\Exception\FileLocked: 423 Locked
```
- the next append rclone notices that the nextcloud file is a different length
```
2019/06/14 12:06:53 DEBUG : rclone_appending.txt: Sizes differ (src 103 vs dst 110)
```
- however it can't find the file when trying to read it from next cloud back to the cache
```
2019/06/14 12:06:53 ERROR : rclone_appending.txt: Failed to copy: failed to open source object: File with name rclone_appending.txt could not be located: Sabre\DAV\Exception\NotFound: 404 Not Found
```

The DELETE is issued from the webdav backend when a PUT request fails.

```
	if err != nil {
		// Give the WebDAV server a chance to get its internal state in order after the
		// error.  The error may have been local in which case we closed the connection.
		// The server may still be dealing with it for a moment. A sleep isn't ideal but I
		// haven't been able to think of a better method to find out if the server has
		// finished - ncw
		time.Sleep(1 * time.Second)
		// Remove failed upload
		_ = o.Remove()
		return err
	}
```

This was put in as part of this change eb84b58d3c728be0834bb3bb39282346a41e6b1c

So to get some internal testing working properly

I've fixed that here - can you give it a go?

https://beta.rclone.org/branch/v1.47.0-131-gb1f1b45b-fix-3263-webdav-delete-beta/ (uploaded in 15-30 mins)

I think the decision for backends to delete half uploaded files is probably a bad one and one I need to correct.  I think this affects the ftp and sftp backends too.

**Comment by wlohman-surfsara** [comment]
Excellent! Thanks!
I tried it, and now, I was able to run that append loop a few times without issues. But it seems the problem is not gone yet.

One of my tests started complaining about file corruption:
```
2019/06/14 17:20:39 DEBUG : &{rclone_appending-beta2.txt (rw)}: Release: 
2019/06/14 17:20:39 DEBUG : rclone_appending-beta2.txt(0xc00046d920): RWFileHandle.Release closing
2019/06/14 17:20:39 DEBUG : rclone_appending-beta2.txt(0xc00046d920): close: 
2019/06/14 17:20:39 DEBUG : rclone_appending-beta2.txt(0xc00046d920): not modified so not transferring
2019/06/14 17:20:39 DEBUG : rclone_appending-beta2.txt(0xc00046d920): >close: err=<nil>
2019/06/14 17:20:39 DEBUG : &{rclone_appending-beta2.txt (rw)}: >Release: err=<nil>
2019/06/14 17:20:39 DEBUG : fuse: -> [ID=0x6c0] Release
2019/06/14 17:20:39 DEBUG : fuse: <- Flush [ID=0x6c2 Node=0x4 Uid=0 Gid=0 Pid=5753] 0x2 fl=0x0 lk=0xdc5111b9253357c6
2019/06/14 17:20:39 DEBUG : &{rclone_appending-beta2.txt (rw)}: Flush: 
2019/06/14 17:20:39 DEBUG : &{rclone_appending-beta2.txt (rw)}: >Flush: err=<nil>
2019/06/14 17:20:39 DEBUG : fuse: -> [ID=0x6c2] Flush
2019/06/14 17:20:40 DEBUG : fuse: <- Write [ID=0x6c3 Node=0x4 Uid=0 Gid=0 Pid=5753] 0x2 7 @61 fl=0 lock=0 ffl=OpenWriteOnly+OpenAppend
2019/06/14 17:20:40 DEBUG : &{rclone_appending-beta2.txt (rw)}: Write: len=7, offset=61
2019/06/14 17:20:40 DEBUG : rclone_appending-beta2.txt: Couldn't find file - need to transfer
2019/06/14 17:20:40 ERROR : rclone_appending-beta2.txt: corrupted on transfer: sizes differ 54 vs 61
2019/06/14 17:20:40 INFO  : rclone_appending-beta2.txt: Removing failed copy
2019/06/14 17:20:40 DEBUG : &{rclone_appending-beta2.txt (rw)}: >Write: written=0, err=open RW handle failed to cache file: corrupted on transfer: sizes differ 54 vs 61
2019/06/14 17:20:40 DEBUG : fuse: -> [ID=0x6c3] Write error=EIO: open RW handle failed to cache file: corrupted on transfer: sizes differ 54 vs 61
2019/06/14 17:20:40 DEBUG : fuse: <- Flush [ID=0x6c4 Node=0x4 Uid=0 Gid=0 Pid=5753] 0x2 fl=0x0 lk=0xdc5111b9253357c6
2019/06/14 17:20:40 DEBUG : &{rclone_appending-beta2.txt (rw)}: Flush: 
2019/06/14 17:20:40 DEBUG : &{rclone_appending-beta2.txt (rw)}: >Flush: err=<nil>
2019/06/14 17:20:40 DEBUG : fuse: -> [ID=0x6c4] Flush
```

From the client side, the file is now only partially readable:
```
cat /mnt/rclone/rclone_appending-beta2.txt
run 1
run 2
run 3
run 4
run 5
run 6
run 7
run 8
run 9
run 10
cat: /mnt/rclone/rclone_appending-beta2.txt: Input/output error
```

And on the server:
```
10.255.0.2 -  [14/Jun/2019:17:20:31 +0200] "PUT /remote.php/nonshib-webdav/rclone_appending-beta2.txt HTTP/1.1" 204 - "-" "rclone/v1.47.0-131-gb1f1b45b-fix-3263-webdav-delete-beta" microsecs:2601331 response_size:0 bytes_received:666 bytes_sent:945 XQO7P1i7UxbKFqghXtJCPgAAAIs - 17982
10.255.0.3 -  [14/Jun/2019:17:20:34 +0200] "PROPFIND /remote.php/nonshib-webdav/rclone_appending-beta2.txt HTTP/1.1" 207 739 "-" "rclone/v1.47.0-131-gb1f1b45b-fix-3263-webdav-delete-beta" microsecs:370438 response_size:739 bytes_received:783 bytes_sent:1657 XQO7Qli7UxbKFqghXtJCPwAAAIs - 17982
10.255.0.3 -  [14/Jun/2019:17:20:34 +0200] "PUT /remote.php/nonshib-webdav/rclone_appending-beta2.txt HTTP/1.1" 423 246 "-" "rclone/v1.47.0-131-gb1f1b45b-fix-3263-webdav-delete-beta" microsecs:2360389 response_size:246 bytes_received:673 bytes_sent:1112 XQO7Qli7UxbKFqghXtJCQAAAAIs - 17982
10.255.0.2 -  [14/Jun/2019:17:20:37 +0200] "GET /remote.php/nonshib-webdav/rclone_appending-beta2.txt HTTP/1.1" 200 61 "-" "rclone/v1.47.0-131-gb1f1b45b-fix-3263-webdav-delete-beta" microsecs:1648823 response_size:61 bytes_received:460 bytes_sent:1203 XQO7RVi7UxbKFqghXtJCQQAAAIs - 17982
10.255.0.2 -  [14/Jun/2019:17:20:37 +0200] "GET /remote.php/nonshib-webdav/rclone_appending-beta2.txt HTTP/1.1" 200 61 "-" "rclone/v1.47.0-131-gb1f1b45b-fix-3263-webdav-delete-beta" microsecs:1648823 response_size:61 bytes_received:460 bytes_sent:1203 XQO7RVi7UxbKFqghXtJCQQAAAIs - 17982
```


About that sleep, ownCloud does some processing after a file upload has been received by the server. And if ownCloud has an objectstore as backend (as opposed to a local filesystem), it needs to upload the file to the objectstore as well. From the client perspective, this is seen as part of the PUT. It's best not to expect that this will be a quick and fast process.

Since from the client side it's impossible to know what storage backend is behind ownCloud, a possible solution might be to retry n times when the error returned is 423?

Not sure if that is a proper solution, I'm just trying to think around the problem that there is so much processing going on behind the scenes that make the process unpredictably slow for the client.

**Comment by ncw** [comment]
I've made webdav retry on 423 errors and I've stuck that in [the latest beta](https://beta.rclone.org) (uploaded in 15-30 mins) which is shortly to become v1.48.  This is controlled by the --low-level-retries flag.

I haven't merged the delete fix yet as I want to work on it some more after the 1.48 release but I think the retry on 423 will probably fix the issue...

**Comment by wlohman-surfsara** [comment]
Ah nice, thank you!
I've been running some tests, and the simple append test I'd been using now goes flawlessly. It still encounters the same 'file locked' situations, but the retry does the trick. Also, the data inside the file is as expected (no missing lines or so)

```
2019/06/17 09:59:58 DEBUG : &{rclone_appending-latest-beta.txt (rw)}: Flush: 
2019/06/17 09:59:58 DEBUG : rclone_appending-latest-beta.txt(0xc0004f9aa0): close: 
2019/06/17 09:59:58 DEBUG : rclone_appending-latest-beta.txt: Sizes differ (src 1096 vs dst 1089)
2019/06/17 09:59:58 DEBUG : pacer: low level retry 1/1 (error "rclone_appending-latest-beta.txt" is locked: OCA\DAV\Connector\Sabre\Exception\FileLocked: 423 Locked)
2019/06/17 09:59:58 DEBUG : pacer: Rate limited, increasing sleep to 20ms
2019/06/17 10:00:11 DEBUG : pacer: Reducing sleep to 15ms
2019/06/17 10:00:11 DEBUG : rclone_appending-latest-beta.txt: Received error: "rclone_appending-latest-beta.txt" is locked: OCA\DAV\Connector\Sabre\Exception\FileLocked: 423 Locked - low level retry 1/10
2019/06/17 10:00:15 DEBUG : pacer: Reducing sleep to 11.25ms
2019/06/17 10:00:15 DEBUG : pacer: Reducing sleep to 10ms
2019/06/17 10:00:15 INFO  : rclone_appending-latest-beta.txt: Copied (replaced existing)
2019/06/17 10:00:15 DEBUG : rclone_appending-latest-beta.txt: transferred to remote
2019/06/17 10:00:15 DEBUG : rclone_appending-latest-beta.txt(0xc0004f9aa0): >close: err=<nil>
2019/06/17 10:00:15 DEBUG : &{rclone_appending-latest-beta.txt (rw)}: >Flush: err=<nil>
2019/06/17 10:00:15 DEBUG : fuse: -> [ID=0x211] Flush
```
I ran this a couple of times without issues, and so now I've also tried appending to a bigger file, one that's bigger than the chunk size of the objectstore backend (ie. 150MB) because I already know that is slow. And that's also going fine now with the retries.

So I can confirm, the issue is gone. Thanks again for your quick responses and action :)

**Comment by ncw** [comment]
I'm glad it is working now :-)

I factored the whole deleting thing into another issue: #3274

I think this needs to be resolved separately.
