### ISSUE TITLE
Failed to get endpoints with Amazon Cloud Drive

### ISSUE THREAD

**Issue by SzaboGabesz** [ncw/rclone#427]
Hi,

I managed to install and configure the app, but after the initial token expires (in one hour), rclone is not able to refresh the token. The error message I get is:

```
root@www:~# rclone ls Default:
2016/04/08 19:45:36 Failed to create file system for "Default:": Failed to get endpoints: Get https://drive.amazonaws.com/drive/v1/account/endpoint: oauth2: cannot fetch token: 400 Bad Request
Response: {"error_description":"The request has an invalid grant parameter : refresh_token","error":"invalid_grant"}
```

I run the command as root, so it's probably not a permission issue.

Details:
 - Rclone version: rclone v1.28
 - OS: Ubuntu 14.04.4 LTS (x64)
 - Storage system: Amazon Cloud Drive

**Comment by ncw** [comment]
Hmm,  try deleting the remote and reconfiguring. 

I have had another report of this - don't know what causes it but that should fix it hopefully.

**Comment by SzaboGabesz** [comment]
Of course I tried that several times before creating this issue. Unfortunately it didn't help. Maybe it has something to do with my amazon settings? I even created a security profile on https://developer.amazon.com and whitelisted it in order to make it work. I provided the client ID and secret, but still no luck. Any other options to set?

**Comment by ncw** [comment]
I think this must be an Amazon problem...

This is the only reference I've manage to find mentioning the error:  yadayada/acd_cli#44

Which country are you in?

Could you send me a the result with `--dump-bodies` of the authentication going wrong? (Send me this by private email to nick@craig-wood.com as it will contain sensitive info).

If you can answer the above I can ask on the ACD developers forum and they may come up with an answer.

Thanks

Nick

**Comment by SzaboGabesz** [comment]
I am from Hungary. I sent you the dump.

Thanks!

**Comment by ncw** [comment]
I've posted a question on the amazon cloud drive dev forum here: https://forums.developer.amazon.com/forums/thread.jspa?threadID=12536

**Comment by SzaboGabesz** [comment]
Thanks!

**Comment by SzaboGabesz** [comment]
We've got a response on the forum.

**Comment by schmorrison** [comment]
I received this issue today, trying to track down a fix without whining, but the link to the forum posted above has moved.

rclone v1.29
VPS(ubuntu14.04)
Storage: googleDrive, Amazon Cloud Drive

I have reconfigured multiple times, however within an hour or so the token expires and the transfer ceases. I noticed that rclone seems to be producing tokens with an expiry that is far to soon.

`2016/05/20 15:44:23 Failed to create file system for "b:/TEST": Failed to get endpoints: HTTP code 401: "401 Unauthorized", reponse body: {"message":"Token has expired"}
`

**Comment by SzaboGabesz** [comment]
The new url for the mentioned thread is: https://forums.developer.amazon.com/questions/22571/invalid-grant-on-oauth-token-refresh.html

**Comment by ncw** [comment]
@schmorrison can you check the time and timezone on your computer? Oauth2 needs both to be accurate.

**Comment by schmorrison** [comment]
> @schmorrison can you check the time and timezone on your computer? Oauth2 needs both to be accurate.

I just did, and I hadn't set the timezone on my VPS as the same timezone I was generating certificates on. I changed the time and timezones, but seem to be getting the same error. However the output from running rclone ls shows a time stamp 6 hours ahead of me, which I think would be GMT+0 rather than GMT+6 where I am. Is it supposed to show GMT in the output?

**Comment by schmorrison** [comment]
I saw the comment you made in #493 and adjusted the VPS and local machine to UTC. Regenerated the certificates on the local machine and moved them to the VPS and ran `rclone ls b:/` which listed files for upwards of 12mins(I definitely saw files that didn't have time to list before setting to UTC) as opposed to the ~2mins prior to the adjustment to UTC. Seems like ACD must be invalidating the token before expiry and is unable to refresh correctly.

I will send the dump-headers output today at some point, hopefully it can provide some clues.

**Comment by ncw** [comment]
Will think about ls and timezones. 

Email the dump headers privately as it will contain sensitive info. nick@craig-wood.com

**Comment by ncw** [comment]
OK Here is beta 3 which
  * does a re-authentication on 401 errors (working as per attempt 2)
  * does a retry on that particular 403 error

http://pub.rclone.org/v1.29-33-g085677d%CE%B2/

In my testing this works perfectly now - hopefully it will for you too.

**Comment by laher** [comment]
This version fixes it for me. Nice one

**Comment by SzaboGabesz** [comment]
Thanks! Working perfectly.

**Comment by pgruetter** [comment]
@ncw Ran into the same problem today. The link you posted gives me a 404, can you please check? Or is the fix already in a release?
Thanks a lot!

**Comment by ajkis** [comment]
@pgruetter Amazon revoked rclone access so atm you cant use it.

**Comment by pgruetter** [comment]
Oh, that's very bad news. Thanks for the response though, found the other issues discussing this now that you mentioned it.
