### ISSUE TITLE
B2 key authorisation suggestion

### ISSUE THREAD

**Issue by hajes** [ncw/rclone#465]
Is there a way to implement auto-auth of B2 key?

It is really annoying to create a new key every day due 24h expiration.

**Comment by ncw** [comment]
rclone should be doing this already - I've never had to make a new key.

What error message do you get?

Can you send me a log with `-v` please of the problem?

Thanks

Nick

**Comment by hajes** [comment]
unfortunately, rclone doesn't do anything automatically. Once, I sync something again I let key expire and send the error message. It was sometnig auth_key experies or so.

After 24hours, key expires and I've to create a new key. Then run rclone config and change a key.

There is reply from BackBlaze when I asked them.

============================

The Authentication token from the Authorize account call will expire every 24 hours. However, if you run b2_authorize_account at least once every 24 hours, the token will be valid. You can call the  b2_authorize_account with the same account ID and application key--it just needs to be re-authorized once every 24 hours.

===========================

**Comment by hajes** [comment]
I had an old version of python 2.7

That may be possible cause since "b2" command didn't work

**Comment by ncw** [comment]
rclone calls the `b2_authorize_account` method every time it starts, and whenever it gets a 401 error so it really shouldn't require you to put a new one in every 24 hours.

rclone doesn't use python so that shouldn't affect things.

Can you send a log with `-v` of it going wrong please?

Thanks

Nick

**Comment by hajes** [comment]
unfortunately, I've no running backup at the moment.

I was getting same error as described in [this thread](https://github.com/ncw/rclone/issues/366)

`x: Failed to copy: Failed to upload: Authorization token has expired (401 expired_auth_token)`

**Comment by ncw** [comment]
That bug I've fixed (I think!).

Are you definitely running rclone v1.29 - check the output of `rclone -V` ?

If you are, can you send me a log of what happens with the `--dump-bodies` flag ideally?  It should start with rclone calling `b2_authorize_account`.  (Delete lines with  authorization in before posting), eg try

    rclone --dump-bodies lsd b2:

**Comment by hajes** [comment]
my bad, I had old version. Now, I've installed v1.29

I let you know by next backup

**Comment by ncw** [comment]
Great, thanks

**Comment by marrie** [comment]
I'm still getting that error actually wiht rclone v 1.33.

Authorization token has expired (401 expired_auth_token)

Using b2 as my  remote.  This might be unrelated but thought I'd report it hee as thei very well could be. Thanks.
 I probably should not worry about it, but I do want my back up to be safe.
Log file here.](https://github.com/ncw/rclone/files/532052/outputarchives.logab.zip)
