### ISSUE TITLE
mounted crypt download error - 500 OOPS: lseek

### ISSUE THREAD

**Issue by scriptzteam** [ncw/rclone#779]
When i want to copy file from server to home pc i got 500 OOPS: lseek, via total commander

**Comment by reticentnz** [comment]
You haven't said which version of rclone you're running, but I'll go ahead and guess that it's v1.33. You need to install a beta version - http://beta.rclone.org/v1.33-52-gaedad89/ where seeking on fuse mounts is fixed.

**Comment by ncw** [comment]
Trying the beta is a good idea if you have't already.  Not sure how you managed to use total commander - over the network?

**Comment by scriptzteam** [comment]
i just pointed via total commander to mounted folder, and its 1.33 no beta :)

**Comment by scriptzteam** [comment]
Okay tried rclone-v1.33-64-gbc414b6β-linux-386 and confirming it works, the error lseek gone.

But now the mount still not updating only when i stop mount and remount again ...

**Comment by ncw** [comment]
Try http://beta.rclone.org/v1.33-79-g77b975d/ which will refresh the mount every 5 minutes by default or how often you want with `--dir-cache-time`
