### ISSUE TITLE
Dropbox error: unexpected HTTP status code 414

### ISSUE THREAD

**Issue by austinginder** [ncw/rclone#84]
While attempting to sync a WordPress directory (locally) into Dropbox, I'm receiving the following errors:

```
2015/06/30 12:51:16 wp-content/plugins/addthis/addthis-toolbox.php: Error deleting metadata: Failed to commit metadata changes: unexpected HTTP status code 414
2015/06/30 12:51:17 Dropbox root 'backup/Sites/examplesite.com: Retrying transaction 1/5
2015/06/30 12:51:17 Dropbox root 'backup/Sites/examplesite.com': Retrying transaction 2/5
2015/06/30 12:51:17 Dropbox root 'backup/Sites/examplesite.com': Retrying transaction 3/5
2015/06/30 12:51:18 Dropbox root 'backup/Sites/examplesite.com': Retrying transaction 4/5
2015/06/30 12:51:18 Dropbox root 'backup/Sites/examplesite.com': Retrying transaction 5/5
2015/06/30 12:51:18 wp-content/plugins/addthis/addthis_settings_functions.php: Failed to copy: Failed to commit metadata changes: unexpected HTTP status code 414
2015/06/30 12:51:18 wp-content/plugins/addthis/addthis_settings_functions.php: Removing failed copy
2015/06/30 12:51:18 wp-content/plugins/addthis/addthis_settings_functions.php: Deleting metadata'
```

I'm using the following command/options:
rclone sync ~/Backup/examplesite.com Dropbox:backup/Sites/examplesite.com --size-only --verbose

**Comment by ncw** [comment]
What happens if you run it again - does it complete properly?  The second time you run it it should only do an incremental.

Another thing to try might be to set `--checkers=1` and `--transfers=1` to see if that makes a difference.

**Comment by austinginder** [comment]
With --checkers=1 and --transfers=1 I'm now receiving a new error: Failed to copy: Failed to commit metadata changes: size_limit: Error: put_delta of datastore (size 10485823L) exceeds size limit 10485760 bytes. This is the first time I'm attempting to sync so I'll give it a try after it finishes up.

**Comment by ncw** [comment]
In https://www.dropbox.com/developers/datastore/docs/http it states that the maximum size of a datastore is 10MiB which corresponds exactly to that `10485823L` number above.  I hadn't noticed that limitation before :-(

How many files are you trying to copy? That would be a useful number to know.

I think the solution for you is for me to implement a flag to not use the datastore which will have various minor consequences for rclone metadata but it should fix actually transferring the files.

At the very least I need to document this limitation.

See #55 for some background.

Thanks for doing the tests

-- Nick

**Comment by austinginder** [comment]
This is a large folder with 189685 files.

**Comment by ncw** [comment]
OK that explains it - thanks.  You'll need the fix to sync this folder...

**Comment by austinginder** [comment]
A flag solution would be great.

**Comment by darren12345** [comment]
I've just hit the same problem. Does the --size-only flag ignore the datastore? Experience suggests no...

Thanks.

**Comment by ncw** [comment]
@darren12345 No, --size-only doesn't ignore the datastore :-(  I'm back from vacation now and I'll fix this soon!

**Comment by ncw** [comment]
This should be all fixed in v1.18!

**Comment by austinginder** [comment]
Awesome work. Thanks so much. Looks like it's working! I was able to sync my large folder with Dropbox using v1.18.

**Comment by ncw** [comment]
@austinginder excellent - thanks for letting me know!

**Comment by allanlaal** [comment]
issue persists in v1.33:

$ rclone copy --checkers=1 --transfers=1 --retries 200 -u L4:/afs/acn dropbox:/acn
2016/12/18 10:13:54 Attempt 1/200 failed with 0 errors and: couldn't list: unexpected HTTP status code 414
2016/12/18 10:13:57 Attempt 2/200 failed with 0 errors and: couldn't list: unexpected HTTP status code 414
2016/12/18 10:14:00 Attempt 3/200 failed with 0 errors and: couldn't list: unexpected HTTP status code 414

**Comment by ncw** [comment]
@allanlaal I think that is a different issue. Perhaps related to https://www.dropboxforum.com/t5/API-support/The-remote-server-returned-an-error-414-Request-URI-Too-Large/td-p/192840

Can you make a new issue please with a log with '-v --dump-headers --retries 1'

Thanks 

Nick
