### ISSUE TITLE
CheckResponse includes trailing linefeed; typo in text

### ISSUE THREAD

**Issue by diamondsw** [ncw/rclone#860]
> What is your rclone version (eg output from `rclone -V`)
1.33 (although issue verified in current code on github)
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Mac OS X 10.12.1 (64-bit), Debian 8 (64-bit, up-to-date)
> Which cloud storage system are you using? (eg Google Drive)
Amazon Cloud Drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync /mydir amazon:/Backup/mydir (irrelevant, really)
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
A bit difficult to obtain in my case; see below.

In client.go/func CheckResponse, there are two issues:
1) A minor misspelling - line 188 says "reponse" rather than "response"
2) When obtaining the response on line 181 ("errBody = string(data)"), it includes a trailing linefeed from the HTTP response. TrimSuffix should do the trick. I'd submit a patch, but I'm not familiar with Go and how it represents linefeeds and similar escape characters.

Why does this matter? I'm writing a simple wrapper with Perl to take the verbose output from rclone and make it a bit more useful to me - keep messages I care about, discard those I don't, etc. Unfortunately when processing incoming text on a line-by-line basis, a stray linebreak really gums up the works. This affects the output in verbose mode, and a given line ends up split across multiple lines of output, and is encountered on separate iterations of the loop. I've put some hackish stuff in there for now to cache the line and reassemble it on the next run through the loop to maintain my internal context, but it seems like it would be simpler to just fix the root cause.

Since I have a wrapper making massive changes to the output text, providing a log isn't terribly feasible, but I think the bug and solution is pretty clear without it.

**Comment by ncw** [comment]
I've fixed that in the go-acd repo here: https://github.com/ncw/go-acd/commit/a3c3df8bf8c4a3b8c5c0e10ec88e914c68ffa977

You can find an rclone beta with this change in http://beta.rclone.org/v1.34-03-g34e7ca9/ (uploaded in 15-30 mins)

**Comment by diamondsw** [comment]
Thanks - this corrects the issues I observed.

I noticed there appears to be a new bug in that output is showing up with backslash escape sequences when printed, e.g.:
pacer: low level retry 1/1 (error HTTP code 500: "500 Internal Server Error": response body: "{\"logref\":\"f94b67d8-a4f5-11e6-9b78-9b784a557eff\",\"message\":\"Internal Server Error\"}")

That's exactly as it prints, complete with backslashes on the response body. I assume that's the change from %v to %q on line 188.

**Comment by ncw** [comment]
Yes that is the change from %v to %q.  I'd say that is working as intended - %q will escape any `\n` that get in the output for instance.  Does that cause you a problem?

**Comment by diamondsw** [comment]
I think it's a bit of an over-broad solution; as the output above shows it escapes things that aren't necessary, such as quotation marks. It's an aesthetic issue at this point; I think you're already covered by the addition of TrimSpace, but if you wanted to cover your bases I think "\r" and "\n" are the only characters likely to need escaping; \r in those pesky Icon files mentioned in #861, and \n in all manner of external text (such as HTTP response headers). Totally up to you. :)

**Comment by diamondsw** [comment]
Using rclone 1.34 I still see the behavior originally reported (improper line feeds, not the extra escaping noted in the beta build). I wonder if it's as simple as inserting a substitution from carriage return/linefeed to escape sequence immediately before output is made to the screen (assuming there is a single routine this flows through). In Perl, something akin to 's/\r/\\r/' and 's/\n/\\n/'. That would fix both this issue and any lingering things from Icon\r files (or prevent them, should you find a way to re-implement that in the future). Just a thought.

**Comment by ncw** [comment]
@diamondsw this will be in the next release -it isn't in 1.34 yet.

**Comment by diamondsw** [comment]
Thanks! Sorry, I was confused by the version numbering. I'm used to a version 1.34betaBlah being a beta prior to 1.34, rather than a new build based off 1.34 (which appears to be how it's used here). So for instance, I thought v1.34-03-g34e7ca9 was a beta prior to 1.34, rather than between 1.34 and 1.35. Am I understanding things properly now? :)

If things are still in the state of the last beta I saw, then you run into the excessive escaping described previously. Not a big deal - still better than before, but could still be refined a touch.

**Comment by diamondsw** [comment]
Similar issue (external data including spurious linefeeds) - I've been seeing raw HTML error pages show up in the verbose output. For instance:

`amazon drive root 'folder': Directory listing error for "folder2/": HTTP code 502: "502 Bad Gateway", reponse body: <html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>We're sorry!</title>
</head>
<body style="padding: 4em; color: black; background-color: white; font-family: Verdana,Arial,Helvetica,sans-serif;">
<h2>We're sorry!</h2>
<p>
An error occurred when we tried to process your request.
Rest assured, we're already working on the problem and expect to resolve it shortly.
</p>
<h2>Désolés!</h2>
<p>
Une erreur s'est produite lorsque nous avons tenté de traiter votre requête.
Soyez assuré que nous travaillons déjà à la résolution du problème que nous pensons trouver très rapidement.
</p>
</body>
</html>`
